// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';

  /*
    depends on the app.mediator for publishing messages
   */
  var errorMngr;

  errorMngr = angular.module('app_errorMngr', ['app_mediator']);

  errorMngr.factory('$exceptionHandler', [
    '$log', 'pubSub', function($log, pubSub) {

      /*
        debugMode = 1 - switched ON
       */
      var _debugMode, _handle, _setDebugMode;
      _debugMode = 1;

      /*
        @function _setDebugMode
        @param val
       */
      _setDebugMode = function(val) {
        if (val === 1 || val === 0) {
          return _debugMode = val;
        } else {
          return false;
        }
      };

      /*
        @function _handle
        @param err - error object
       */
      _handle = function(err) {
        if (typeof err !== "object") {
          return false;
        }
        if (err.debug != null) {
          _setDebugMode(err.debug);
          return true;
        }
        if (err.message !== '') {
          if (_debugMode === 1) {
            switch (err.type) {
              case 'error':
                $log.error(err.message);
                break;
              case 'log':
                $log.log(err.message);
                break;
              case 'info':
                $log.info(err.message);
                break;
              case 'warn':
                $log.warn(err.message);
                break;
              default:
                $log.log(err.message);
                $log.log(err.stack);
            }
          }
          if (err.display != null) {
            if (err.display === true) {
              return pubSub.publish({
                msg: "Display error to frontend",
                msgScope: ["error"],
                data: err.message
              });
            }
          }
        } else {
          return false;
        }
      };
      return function(exception) {
        return _handle(exception);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=errorMngr.js.map
