// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseModuleMessageService, DataWranglerMsgService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModuleMessageService = require('scripts/BaseClasses/BaseModuleMessageService.coffee');

  module.exports = DataWranglerMsgService = (function(superClass) {
    extend(DataWranglerMsgService, superClass);

    function DataWranglerMsgService() {
      return DataWranglerMsgService.__super__.constructor.apply(this, arguments);
    }

    DataWranglerMsgService.prototype.msgList = {
      outgoing: ['getData', 'saveData'],
      incoming: ['takeTable'],
      scope: ['app_analysis_dataWrangler']
    };

    return DataWranglerMsgService;

  })(BaseModuleMessageService);

}).call(this);

//# sourceMappingURL=DataWranglerMsgService.service.js.map
