// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var Module, dataWrangler;

  Module = require('scripts/BaseClasses/BaseModule.coffee');

  module.exports = dataWrangler = new Module({
    id: 'app_analysis_dataWrangler',
    components: {
      services: {
        'app_analysis_dataWrangler_initService': require('scripts/analysis/DataWrangler/DataWranglerInit.service.coffee'),
        'app_analysis_dataWrangler_msgService': require('scripts/analysis/DataWrangler/DataWranglerMsgService.service.coffee'),
        'app_analysis_dataWrangler_dataAdaptor': require('scripts/analysis/DataWrangler/DataWranglerDataAdaptor.service.coffee'),
        'app_analysis_dataWrangler_dataService': require('scripts/analysis/DataWrangler/DataWranglerDataService.service.coffee'),
        'app_analysis_dataWrangler_wrangler': require('scripts/analysis/DataWrangler/DataWranglerWrangler.service.coffee')
      },
      controllers: {
        'DataWranglerSidebarCtrl': require('scripts/analysis/DataWrangler/DataWranglerSidebarCtrl.controller.coffee'),
        'DataWranglerMainCtrl': require('scripts/analysis/DataWrangler/DataWranglerMainCtrl.controller.coffee')
      },
      directives: {
        'wranglerdir': require('scripts/analysis/DataWrangler/DataWranglerWranglerDir.directive.coffee')
      }
    },
    state: {
      name: 'Data Wrangler',
      url: '/dataWrangler',
      mainTemplate: require('partials/analysis/DataWrangler/main.jade'),
      sidebarTemplate: require('partials/analysis/DataWrangler/sidebar.jade')
    }
  });

}).call(this);

//# sourceMappingURL=DataWrangler.module.js.map
