// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseModuleDataService, DataWranglerDataService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModuleDataService = require('scripts/BaseClasses/BaseModuleDataService.coffee');

  module.exports = DataWranglerDataService = (function(superClass) {
    extend(DataWranglerDataService, superClass);

    function DataWranglerDataService() {
      return DataWranglerDataService.__super__.constructor.apply(this, arguments);
    }

    DataWranglerDataService.inject('$q', 'app_analysis_dataWrangler_msgService');

    DataWranglerDataService.prototype.initialize = function() {
      this.msgManager = this.app_analysis_dataWrangler_msgService;
      this.getDataRequest = this.msgManager.getMsgList().outgoing[0];
      this.getDataResponse = this.msgManager.getMsgList().incoming[0];
      return this.saveDataMsg = this.msgManager.getMsgList().outgoing[1];
    };

    return DataWranglerDataService;

  })(BaseModuleDataService);

}).call(this);

//# sourceMappingURL=DataWranglerDataService.service.js.map
