// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseService, ChartsAreaChart,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseService = require('scripts/BaseClasses/BaseService.coffee');

  module.exports = ChartsAreaChart = (function(superClass) {
    extend(ChartsAreaChart, superClass);

    function ChartsAreaChart() {
      return ChartsAreaChart.__super__.constructor.apply(this, arguments);
    }

    ChartsAreaChart.prototype.initialize = function() {};

    ChartsAreaChart.prototype.drawArea = function(height, width, _graph, data, gdata) {
      var area, d, i, len, x, xAxis, y, yAxis;
      for (i = 0, len = data.length; i < len; i++) {
        d = data[i];
        d.x = new Date(d.x);
        d.y = +d.y;
      }
      x = d3.time.scale().range([0, width]);
      y = d3.scale.linear().range([height, 0]);
      xAxis = d3.svg.axis().scale(x).orient("bottom");
      yAxis = d3.svg.axis().scale(y).orient("left");
      area = d3.svg.area().x(function(d) {
        return x(d.x);
      }).y0(height).y1(function(d) {
        return y(d.y);
      });
      x.domain(d3.extent(data, function(d) {
        return d.x;
      }));
      y.domain([
        0, d3.max(data, function(d) {
          return d.y;
        })
      ]);
      _graph.append("path").datum(data).attr("class", "area").attr("d", area);
      _graph.append("g").attr("class", "x axis").attr("transform", "translate(0," + height + ")").call(xAxis);
      return _graph.append("g").attr("class", "y axis").call(yAxis).append("text").attr("transform", "rotate(-90)").attr("y", 6).attr("dy", ".71em").style("text-anchor", "end").text(gdata.yLab.value);
    };

    return ChartsAreaChart;

  })(BaseService);

}).call(this);

//# sourceMappingURL=ChartsAreaChart.service.js.map
