// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var ChartsMsgService, ModuleMessageService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ModuleMessageService = require('scripts/BaseClasses/BaseModuleMessageService.coffee');

  module.exports = ChartsMsgService = (function(superClass) {
    extend(ChartsMsgService, superClass);

    function ChartsMsgService() {
      return ChartsMsgService.__super__.constructor.apply(this, arguments);
    }

    ChartsMsgService.prototype.msgList = {
      outgoing: ['getData', 'infer data types'],
      incoming: ['takeTable', 'data types inferred'],
      scope: ['app_analysis_charts']
    };

    return ChartsMsgService;

  })(ModuleMessageService);

}).call(this);

//# sourceMappingURL=ChartsMsgService.service.js.map
