// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseModuleDataService, ChartsDataService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModuleDataService = require('scripts/BaseClasses/BaseModuleDataService.coffee');

  module.exports = ChartsDataService = (function(superClass) {
    extend(ChartsDataService, superClass);

    function ChartsDataService() {
      return ChartsDataService.__super__.constructor.apply(this, arguments);
    }

    ChartsDataService.inject('$q', 'app_analysis_charts_msgService');

    ChartsDataService.prototype.initialize = function() {
      this.msgManager = this.app_analysis_charts_msgService;
      this.getDataRequest = this.msgManager.getMsgList().outgoing[0];
      return this.getDataResponse = this.msgManager.getMsgList().incoming[0];
    };

    ChartsDataService.prototype.inferDataTypes = function(data, cb) {
      return this.post(this.msgManager.getMsgList().outgoing[1], this.msgManager.getMsgList().incoming[1], data).then((function(_this) {
        return function(resp) {
          return cb(resp);
        };
      })(this));
    };

    return ChartsDataService;

  })(BaseModuleDataService);

}).call(this);

//# sourceMappingURL=ChartsDataService.service.js.map
