// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseService, ChartsDataTransform,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseService = require('scripts/BaseClasses/BaseService.coffee');

  module.exports = ChartsDataTransform = (function(superClass) {
    extend(ChartsDataTransform, superClass);

    function ChartsDataTransform() {
      return ChartsDataTransform.__super__.constructor.apply(this, arguments);
    }

    ChartsDataTransform.prototype.initialize = function() {};

    ChartsDataTransform.prototype.transpose = function(data) {
      return data[0].map(function(col, i) {
        return data.map(function(row) {
          return row[i];
        });
      });
    };

    ChartsDataTransform.prototype.transform = function(data) {
      var col, i, j, k, len, len1, obj, results, value;
      results = [];
      for (j = 0, len = data.length; j < len; j++) {
        col = data[j];
        obj = {};
        for (i = k = 0, len1 = col.length; k < len1; i = ++k) {
          value = col[i];
          obj[i] = value;
        }
        results.push(d3.entries(obj));
      }
      return results;
    };

    ChartsDataTransform.prototype.format = function(data) {
      return this.transform(this.transpose(data));
    };

    return ChartsDataTransform;

  })(BaseService);

}).call(this);

//# sourceMappingURL=ChartsDataTransform.service.js.map
