// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var ChartsInitService, ModuleInitService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ModuleInitService = require('scripts/BaseClasses/BaseModuleInitService.coffee');

  module.exports = ChartsInitService = (function(superClass) {
    extend(ChartsInitService, superClass);

    function ChartsInitService() {
      return ChartsInitService.__super__.constructor.apply(this, arguments);
    }

    ChartsInitService.inject('app_analysis_charts_msgService');

    ChartsInitService.prototype.initialize = function() {
      this.msgService = this.app_analysis_charts_msgService;
      return this.setMsgList();
    };

    return ChartsInitService;

  })(ModuleInitService);

}).call(this);

//# sourceMappingURL=ChartsInit.service.js.map
