// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var Module, db;

  Module = require('scripts/BaseClasses/BaseModule.coffee');

  module.exports = db = new Module({
    id: 'app_analysis_datalib',
    components: {
      services: {
        'app_analysis_datalib_initService': require('scripts/analysis/Datalib/DatalibInit.service.coffee'),
        'app_analysis_datalib_msgService': require('scripts/analysis/Datalib/DatalibMsgService.service.coffee'),
        'app_analysis_datalib_dataAdaptor': require('scripts/analysis/Datalib/DatalibDataAdaptor.service.coffee'),
        'app_analysis_datalib_api': require('scripts/analysis/Datalib/DatalibApi.service.coffee'),
        'app_analysis_datalib_wrapper': require('scripts/analysis/Datalib/DatalibWrapper.service.coffee')
      },
      runBlock: require('scripts/analysis/Datalib/DatalibRunBlock.run.coffee')
    }
  });

}).call(this);

//# sourceMappingURL=Datalib.module.js.map
