// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseModuleInitService, DatalibInitService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModuleInitService = require('scripts/BaseClasses/BaseModuleInitService.coffee');

  module.exports = DatalibInitService = (function(superClass) {
    extend(DatalibInitService, superClass);

    function DatalibInitService() {
      return DatalibInitService.__super__.constructor.apply(this, arguments);
    }

    DatalibInitService.inject('app_analysis_datalib_msgService');

    DatalibInitService.prototype.initialize = function() {
      this.msgService = this.app_analysis_datalib_msgService;
      return this.setMsgList();
    };

    return DatalibInitService;

  })(BaseModuleInitService);

}).call(this);

//# sourceMappingURL=DatalibInit.service.js.map
