// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var Module, getData;

  Module = require('scripts/BaseClasses/BaseModule.coffee');

  module.exports = getData = new Module({
    id: 'app_analysis_getData',
    components: {
      services: {
        'app_analysis_getData_initService': require('scripts/analysis/GetData/GetDataInit.service.coffee'),
        'app_analysis_getData_msgService': require('scripts/analysis/GetData/GetDataMsgService.service.coffee'),
        'app_analysis_getData_dataAdaptor': require('scripts/analysis/GetData/GetDataDataAdaptor.service.coffee'),
        'app_analysis_getData_inputCache': require('scripts/analysis/GetData/GetDataInputCache.service.coffee'),
        'app_analysis_getData_jsonParser': require('scripts/analysis/GetData/GetDataJsonParser.service.coffee'),
        'app_analysis_getData_showState': require('scripts/analysis/GetData/GetDataShowState.service.coffee'),
        'app_analysis_getData_dataService': require('scripts/analysis/GetData/GetDataDataService.service.coffee')
      },
      controllers: {
        'GetDataSidebarCtrl': require('scripts/analysis/GetData/GetDataSidebarCtrl.controller.coffee'),
        'GetDataMainCtrl': require('scripts/analysis/GetData/GetDataMainCtrl.controller.coffee')
      },
      directives: {
        'getdatadragndrop': require('scripts/analysis/GetData/GetDataDragNDropDir.directive.coffee')
      }
    },
    state: {
      name: 'Raw Data',
      url: '/getData',
      mainTemplate: require('partials/analysis/getData/main.jade'),
      sidebarTemplate: require('partials/analysis/getData/sidebar.jade')
    },
    deps: ['ngHandsontable']
  });

}).call(this);

//# sourceMappingURL=GetData.module.js.map
