// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseModuleMessageService, GetDataMsgService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModuleMessageService = require('scripts/BaseClasses/BaseModuleMessageService.coffee');

  module.exports = GetDataMsgService = (function(superClass) {
    extend(GetDataMsgService, superClass);

    function GetDataMsgService() {
      return GetDataMsgService.__super__.constructor.apply(this, arguments);
    }

    GetDataMsgService.prototype.msgList = {
      outgoing: ['getData', 'saveData'],
      incoming: ['takeTable', 'getData'],
      scope: ['app_analysis_getData']
    };

    return GetDataMsgService;

  })(BaseModuleMessageService);

}).call(this);

//# sourceMappingURL=GetDataMsgService.service.js.map
