// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseService, DatabaseRunBlock;

  BaseService = require('scripts/BaseClasses/BaseService.coffee');


  /*
    @name DatabaseRunBlock
    @desc Class for database run block
   */

  module.exports = DatabaseRunBlock = (function() {
    function DatabaseRunBlock(module1) {
      this.module = module1;
    }

    DatabaseRunBlock.prototype.register = function() {
      return this.module.run(this.getDbRunBlock());
    };

    DatabaseRunBlock.prototype.getDbRunBlock = function() {
      var runBlock;
      runBlock = function(app_analysis_database_handler) {
        app_analysis_database_handler.initDb();
        return console.log('db: run block');
      };
      runBlock.$inject = ['app_analysis_database_handler'];
      return runBlock;
    };

    return DatabaseRunBlock;

  })();

}).call(this);

//# sourceMappingURL=DatabaseRunBlock.run.js.map
