// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseModuleInitService, DatabaseInitService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModuleInitService = require('scripts/BaseClasses/BaseModuleInitService.coffee');

  module.exports = DatabaseInitService = (function(superClass) {
    extend(DatabaseInitService, superClass);

    function DatabaseInitService() {
      return DatabaseInitService.__super__.constructor.apply(this, arguments);
    }

    DatabaseInitService.inject('app_analysis_database_msgService');

    DatabaseInitService.prototype.initialize = function() {
      this.msgService = this.app_analysis_database_msgService;
      return this.setMsgList();
    };

    return DatabaseInitService;

  })(BaseModuleInitService);

}).call(this);

//# sourceMappingURL=DatabaseInit.service.js.map
