// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseService, DatabaseNestedStorage,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseService = require('scripts/BaseClasses/BaseService.coffee');


  /*
    @name: DatabaseNestedStorage
    @desc: Stores non-flat, hierarchical data
   */

  module.exports = DatabaseNestedStorage = (function(superClass) {
    extend(DatabaseNestedStorage, superClass);

    function DatabaseNestedStorage() {
      return DatabaseNestedStorage.__super__.constructor.apply(this, arguments);
    }

    DatabaseNestedStorage.prototype.initialize = function() {
      return this.nestedObj = null;
    };

    DatabaseNestedStorage.prototype.save = function(obj) {
      return this.nestedObj = obj;
    };

    DatabaseNestedStorage.prototype.get = function() {
      return this.nestedObj;
    };

    return DatabaseNestedStorage;

  })(BaseService);

}).call(this);

//# sourceMappingURL=DatabaseNestedStorage.service.js.map
