// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseModuleMessageService, DatabaseMsgService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModuleMessageService = require('scripts/BaseClasses/BaseModuleMessageService.coffee');

  module.exports = DatabaseMsgService = (function(superClass) {
    extend(DatabaseMsgService, superClass);

    function DatabaseMsgService() {
      return DatabaseMsgService.__super__.constructor.apply(this, arguments);
    }

    DatabaseMsgService.prototype.msgList = {
      incoming: ['save table', 'create table', 'get table', 'delete table'],
      outgoing: ['table saved', 'table created', 'take table', 'table deleted'],
      scope: ['app_analysis_database']
    };

    return DatabaseMsgService;

  })(BaseModuleMessageService);

}).call(this);

//# sourceMappingURL=DatabaseMsgService.service.js.map
