// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseCtrl, MyModuleMainCtrl,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseCtrl = require('scripts/BaseClasses/BaseController.coffee');

  module.exports = MyModuleMainCtrl = (function(superClass) {
    extend(MyModuleMainCtrl, superClass);

    function MyModuleMainCtrl() {
      return MyModuleMainCtrl.__super__.constructor.apply(this, arguments);
    }

    MyModuleMainCtrl.inject('app_analysis_mymodule_dataService', '$timeout', '$scope');

    MyModuleMainCtrl.prototype.initialize = function() {
      this.dataService = this.app_analysis_mymodule_dataService;
      this.DATA_TYPES = this.dataService.getDataTypes();
      return this.$scope.$on('MyModule:updateDataType', (function(_this) {
        return function(event, dataType) {
          _this.dataType = dataType;
          return console.log("I received data");
        };
      })(this));
    };

    return MyModuleMainCtrl;

  })(BaseCtrl);

}).call(this);

//# sourceMappingURL=MyModuleMainCtrl.ctrl.js.map
