// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseModuleDataService, MyModuleDataService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModuleDataService = require('scripts/BaseClasses/BaseModuleDataService.coffee');

  module.exports = MyModuleDataService = (function(superClass) {
    extend(MyModuleDataService, superClass);

    function MyModuleDataService() {
      return MyModuleDataService.__super__.constructor.apply(this, arguments);
    }

    MyModuleDataService.inject('$q', 'app_analysis_mymodule_msgService');

    MyModuleDataService.prototype.initialize = function() {
      this.msgManager = this.app_analysis_MyModule_msgService;
      this.getDataRequest = this.msgManager.getMsgList().outgoing[0];
      return this.getDataResponse = this.msgManager.getMsgList().incoming[0];
    };

    return MyModuleDataService;

  })(BaseModuleDataService);

}).call(this);

//# sourceMappingURL=MyModuleDataService.service.js.map
