// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var Module, myModule;

  Module = require('scripts/BaseClasses/BaseModule.coffee');

  module.exports = myModule = new Module({
    id: 'app_analysis_mymodule',
    components: {
      services: {
        'app_analysis_mymodule_initService': require('scripts/analysis/tools/MyModule/MyModuleInit.service.coffee'),
        'app_analysis_mymodule_msgService': require('scripts/analysis/tools/MyModule/MyModuleMsgService.service.coffee'),
        'app_analysis_mymodule_dataService': require('scripts/analysis/tools/MyModule/MyModuleDataService.service.coffee'),
        'app_analysis_mymodule_myService': require('scripts/analysis/tools/MyModule/MyModuleMyService.service.coffee')
      },
      controllers: {
        'mymoduleMainCtrl': require('scripts/analysis/tools/MyModule/MyModuleMainCtrl.ctrl.coffee'),
        'mymoduleSidebarCtrl': require('scripts/analysis/tools/MyModule/MyModuleSidebarCtrl.ctrl.coffee')
      },
      directives: {
        'appMyModuleDir': require('scripts/analysis/tools/MyModule/MyModuleDir.directive.coffee')
      }
    },
    state: {
      name: 'My Awesome Module',
      url: '/tools/mymodule',
      mainTemplate: require('partials/analysis/tools/MyModule/main.jade'),
      sidebarTemplate: require('partials/analysis/tools/MyModule/sidebar.jade')
    }
  });

}).call(this);

//# sourceMappingURL=MyModule.module.js.map
