// Generated by CoffeeScript 1.12.2
(function() {
  describe("app_utils module", function() {
    return beforeEach(function() {
      module("app_utils");
      return describe("databridge service", function() {
        return it("first unit test case", function() {
          return inject(function(app_utils_databridge) {
            return expect(true).toBe(true);
          });
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=databridge.spec.js.map
