// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseModuleMessageService, ClusterMsgService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModuleMessageService = require('scripts/BaseClasses/BaseModuleMessageService.coffee');

  module.exports = ClusterMsgService = (function(superClass) {
    extend(ClusterMsgService, superClass);

    function ClusterMsgService() {
      return ClusterMsgService.__super__.constructor.apply(this, arguments);
    }

    ClusterMsgService.prototype.msgList = {
      outgoing: ['getData', 'infer data types'],
      incoming: ['takeTable', 'data types inferred'],
      scope: ['app_analysis_cluster']
    };

    return ClusterMsgService;

  })(BaseModuleMessageService);

}).call(this);

//# sourceMappingURL=ClusterMsgService.service.js.map
