// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var Module, cluster;

  Module = require('scripts/BaseClasses/BaseModule.coffee');

  module.exports = cluster = new Module({
    id: 'app_analysis_cluster',
    components: {
      services: {
        'app_analysis_cluster_initService': require('scripts/analysis/tools/Cluster/ClusterInit.service.coffee'),
        'app_analysis_cluster_msgService': require('scripts/analysis/tools/Cluster/ClusterMsgService.service.coffee'),
        'app_analysis_cluster_dataService': require('scripts/analysis/tools/Cluster/ClusterDataService.service.coffee'),
        'app_analysis_cluster_algorithms': require('scripts/analysis/tools/Cluster/ClusterAlgorithms.service.coffee'),
        'app_analysis_cluster_metrics': require('scripts/analysis/tools/Cluster/ClusterMetrics.service.coffee'),
        'app_analysis_cluster_kMeans': require('scripts/analysis/tools/Cluster/ClusterKMeans.service.coffee'),
        'app_analysis_cluster_spectral': require('scripts/analysis/tools/Cluster/ClusterSpectral.service.coffee')
      },
      controllers: {
        'clusterMainCtrl': require('scripts/analysis/tools/Cluster/ClusterMainCtrl.ctrl.coffee'),
        'clusterSidebarCtrl': require('scripts/analysis/tools/Cluster/ClusterSidebarCtrl.ctrl.coffee')
      },
      directives: {
        'socratClusterViz': require('scripts/analysis/tools/Cluster/ClusterVizDir.directive.coffee')
      }
    },
    state: {
      name: 'Clustering',
      url: '/tools/cluster',
      mainTemplate: require('partials/analysis/tools/cluster/main.jade'),
      sidebarTemplate: require('partials/analysis/tools/cluster/sidebar.jade')
    }
  });

}).call(this);

//# sourceMappingURL=Cluster.module.js.map
