// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseModuleInitService, ClusterInitService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModuleInitService = require('scripts/BaseClasses/BaseModuleInitService.coffee');

  module.exports = ClusterInitService = (function(superClass) {
    extend(ClusterInitService, superClass);

    function ClusterInitService() {
      return ClusterInitService.__super__.constructor.apply(this, arguments);
    }

    ClusterInitService.inject('app_analysis_cluster_msgService');

    ClusterInitService.prototype.initialize = function() {
      this.msgService = this.app_analysis_cluster_msgService;
      return this.setMsgList();
    };

    return ClusterInitService;

  })(BaseModuleInitService);

}).call(this);

//# sourceMappingURL=ClusterInit.service.js.map
