// Generated by CoffeeScript 1.12.2
(function() {
  var toolkit;

  toolkit = angular.module('app.utils.toolkit', []);

  toolkit.run([
    function() {
      return console.log('run block of app.utils.toolkit');
    }
  ]);

  toolkit.factory('app.utils.toolkit.toCSV', [
    function() {
      return function(data) {
        return data;
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=toolkit.js.map
