// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var BaseModuleMessageService, ReliabilityMsgService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseModuleMessageService = require('scripts/BaseClasses/BaseModuleMessageService.coffee');

  module.exports = ReliabilityMsgService = (function(superClass) {
    extend(ReliabilityMsgService, superClass);

    function ReliabilityMsgService() {
      return ReliabilityMsgService.__super__.constructor.apply(this, arguments);
    }

    ReliabilityMsgService.prototype.msgList = {
      outgoing: ['getData', 'infer data types'],
      incoming: ['takeTable', 'data types inferred'],
      scope: ['app_analysis_reliability']
    };

    return ReliabilityMsgService;

  })(BaseModuleMessageService);

}).call(this);

//# sourceMappingURL=ReliabilityMsgService.service.js.map
