// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';

  /*
    @name BaseCtrl
    @desc Base class for Angular controllers
   */
  var BaseCtrl,
    slice = [].slice;

  module.exports = BaseCtrl = (function() {
    BaseCtrl.register = function(module, name) {
      var ref;
      if (name == null) {
        name = this.name || ((ref = this.toString().match(/function\s*(.*?)\(/)) != null ? ref[1] : void 0);
      }
      return module.controller(name, this);
    };

    BaseCtrl.inject = function() {
      var ANNOTATION_REG, annotations;
      annotations = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      ANNOTATION_REG = /^(\S+)(\s+as\s+(\w+))?$/;
      this.annotations = annotations.map(function(annotation) {
        var match;
        match = annotation.match(ANNOTATION_REG);
        return {
          name: match[1],
          identifier: match[3] || match[1]
        };
      });
      return this.$inject = this.annotations.map(function(annotation) {
        return annotation.name;
      });
    };

    function BaseCtrl() {
      var annotation, dependencies, i, index, len, ref;
      dependencies = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      if (dependencies.length) {
        ref = this.constructor.annotations;
        for (index = i = 0, len = ref.length; i < len; index = ++i) {
          annotation = ref[index];
          this[annotation.identifier] = dependencies[index];
        }
        if (typeof this.initialize === "function") {
          this.initialize();
        }
      }
    }

    return BaseCtrl;

  })();

}).call(this);

//# sourceMappingURL=BaseController.js.map
