// ---------------------------------------------------------------------------------------------------------------------
// jsstrings_en.js
// ---------------------------------------------------------------------------------------------------------------------
// WARNING: Computer generated file.  Do not hand modify.
// DEPENDS ON: ['scriptsharp/src/Resources/Strings/Strings.en.resx', 'scriptsharp/src/Resources/Strings/resx-strings-js.template']

(function(w) {
  var s = {
    AODialogBandTabTitle: "Band",
    AODialogCellScope: "Cell",
    AODialogComputationLabel: "Computation",
    AODialogCustomLabelLabel: "Custom Label",
    AODialogCustomTooltipLabel: "Custom Tooltip",
    AODialogDistributionTabTitle: "Distribution",
    AODialogFactorsLabel: "Factors",
    AODialogFromValueLabel: "Value (From)",
    AODialogInstantAnalyticsBandLabel: "Recalculate band for selected data",
    AODialogInstantAnalyticsLineLabel: "Recalculate line for selected data",
    AODialogLabelLabel: "Label",
    AODialogLineTabTitle: "Line",
    AODialogNumberOfTilesLabel: "Number Of Tiles",
    AODialogPaneScope: "Pane",
    AODialogPercentOfLabel: "Percent Of",
    AODialogPercentagesLabel: "Percentages",
    AODialogPercentilesLabel: "Percentiles",
    AODialogQuantiles: "Quantiles",
    AODialogStandardDeviation: "Standard Deviation",
    AODialogTableScope: "Table",
    AODialogTitleString: "Edit {0}",
    AODialogToValueLabel: "Value (To)",
    AODialogTooltipLabel: "Tooltip",
    AODialogValueLabel: "Value",
    AccelerationDisallowedTooltip: "This view cannot be accelerated because {0}",
    AccelerationOffTooltip: "Acceleration is off for this view, click to turn on acceleration.",
    AccelerationOnTooltip: "Acceleration is on for this view, click to turn off acceleration.",
    AccelerationPendingTooltip: "Acceleration is Pending for this view, click to turn off acceleration.",
    AccessbilityNotificationButtonDismissLabel: "Dismiss Notification",
    AccessibilityClearSelectionInstructions: "Press ESC to clear any mark selections.",
    AccessibilityDataVisualizationTitleAttr: "Data Visualization",
    AccessibilityScrollSheetTabsLeft: "Scroll Sheet Tabs Left",
    AccessibilityScrollSheetTabsRight: "Scroll Sheet Tabs Right",
    AccessibilityTypeInFieldPrompt: "After typing a new value, press ENTER to commit.",
    AccessibilityViewDataDisabled: "Access to the View Data window is not enabled.",
    AccessibilityViewDataInstructions: "To open the View Data window, press Control-Shift-Enter.",
    AddALayer: "Add a|Marks Layer",
    AddDataConnection: "Add data source",
    AddDataConnectionAdd: "Add",
    AddDataConnectionCancel: "Cancel",
    AddDataExplanation: "Select a published data source to add it to your workbook.",
    AddDataLearnMore: "Learn more",
    AddDataLearnToPublish: "Learn how to publish data sources to Tableau Server.",
    AddDataNoPublishedDataSources: "There are no data sources available.",
    AddDataNoSearchMatches: "No data sources matched your search term.",
    AddDataPublishRequirements: "To publish a new data source, you must be a Publisher for {0}.",
    AddDataSearchBrowseSuggestion: "Scroll to browse the list of available data sources.",
    AddDataSearchDifferentTermsSuggestion: "Try again with different terms.",
    AddDataSearchSpellingSuggestion: "Check your spelling.",
    AddDataSearchSuggestions: "Search suggestions:",
    AddDesktopLayout: "Add Desktop Layout",
    AddFloatingTextZoneInStoriesLabel: "Drag to add text",
    AddPhoneLayout: "Add Phone Layout",
    AddSubscribers: "Add",
    AddSubscribersHeader: "Add Subscribers",
    AddTabletLayout: "Add Tablet Layout",
    AddToLabel: "Add to:",
    AggregateCalcWarning: "This field contains an aggregate calculation which only contains meaningful data in the visualization\'s level of detail.",
    AliasDialogHasAliasColumn: "Has Alias",
    AliasDialogMemberColumn: "Member",
    AliasDialogValueColumn: "Value (Alias)",
    AnalyticsExtensionGenericErrorMsg: "Unable to proceed because of an error from the Analytics Extension.",
    AnalyticsExtensionGenericErrorSubMsg: "Try connecting again. If the problem persists contact the Analytics Extension owner.",
    AnalyticsExtensionGenericTitle: "Analytics Extension Error",
    AnimationServerRenderingInfoToastMessage: "Animations are paused for this complex viz. Try filtering out more data.",
    April: "April",
    AprilNarrow: "A",
    AprilShort: "Apr",
    AreYouSureDelete: "Delete",
    AskDataToolbarButtonLabel: "Ask Data",
    August: "August",
    AugustNarrow: "A",
    AugustShort: "Aug",
    AuthAutoSaveWarningDialogCancel: "Close",
    AuthAutoSaveWarningDialogPublishButton: "Publish Now",
    AuthAutosaveLearnMore: "Learn more",
    AuthCardCollapsedTitle: "{0} &middot; {1}",
    AuthCardTitleColumns: "Columns",
    AuthCardTitleFilters: "Filters",
    AuthCardTitleMarks: "Marks",
    AuthCardTitleMeasureValues: "Measure Values",
    AuthCardTitleMetricsDataFilters: "Data Filters",
    AuthCardTitlePages: "Pages",
    AuthCardTitleRows: "Rows",
    AuthColorEditingDisabled: "Combine legends to edit colors here or edit the colors for each individual legend.",
    AuthColorPaletteAutomatic: "Automatic",
    AuthColorPaletteLegacy: "Discontinued",
    AuthColorPaletteMoreColors: "More Colors...",
    AuthColorPaletteNone: "None",
    AuthColorTransparencyLabel: "Opacity",
    AuthConnectToDataSource: "Connect to a Data Source on {0}",
    AuthCustomHexColorLabel: "Custom Color",
    AuthDashboardPaneBlankZone: "Blank",
    AuthDashboardPaneCarouselZone: "Carousel",
    AuthDashboardPaneExportButtonZone: "Download",
    AuthDashboardPaneExtensionZone: "Extension",
    AuthDashboardPaneFloatingButton: "Floating",
    AuthDashboardPaneGridContainer: "Grid",
    AuthDashboardPaneHorizontalStack: "Horizontal",
    AuthDashboardPaneHorizontalZone: "Horizontal",
    AuthDashboardPaneImageZone: "Image",
    AuthDashboardPaneNavigationButtonZone: "Navigation",
    AuthDashboardPaneNewObjects: "New Objects:",
    AuthDashboardPaneSheets: "Sheets",
    AuthDashboardPaneSize: "Size - {0}",
    AuthDashboardPaneSizeDefault: "Size",
    AuthDashboardPaneSizeFitAll: "Fit all",
    AuthDashboardPaneSizeFitDefault: "Default",
    AuthDashboardPaneSizeFitWidth: "Fit width",
    AuthDashboardPaneSnapshotButtonZone: "Snapshot",
    AuthDashboardPaneTextZone: "Text",
    AuthDashboardPaneTiledButton: "Tiled",
    AuthDashboardPaneTitleCheckbox: "Show dashboard title",
    AuthDashboardPaneVerticalStack: "Vertical",
    AuthDashboardPaneVerticalZone: "Vertical",
    AuthDashboardPaneWebZone: "Web Page",
    AuthDashboardPaneZoneObjects: "Objects",
    AuthDraftNotCurrentDialogEditNewestRevision: "Edit Newest Revision",
    AuthDraftNotCurrentDialogMessage: "An updated revision of this workbook was published on {0} by {1}. Do you want to discard your draft and edit the current revision?",
    AuthDraftNotCurrentDialogMessage_NoUsername: "An updated revision of this workbook was published on {0}. Do you want to discard your draft and edit the current revision?",
    AuthDraftNotCurrentDialogResumeEditingDraft: "Resume Editing My Draft",
    AuthDraftNotCurrentDialogTitle: "Draft Not Current",
    AuthFirstPublishInformationToastText: "After you publish the first time, we\'ll start to autosave your changes to a draft.",
    AuthFirstPublishInformationToastTitle: "Click Publish to save your changes",
    AuthFontFamilyAndSize: "{0} {1}",
    AuthFontListLoading: "Loading…",
    AuthFormatLineVisibilityAutomatic: "Automatic",
    AuthFormatLineVisibilityOff: "Off",
    AuthFormatLineVisibilityOn: "On",
    AuthFormatSectionCollapse: "Less",
    AuthFormatSectionExpand: "More",
    AuthHeatmapIntensityLabel: "Intensity",
    AuthIncludeTotalsLabel: "Include Totals",
    AuthLabelEditingDisabledDrag: "In order to edit mark text, drag dimensions or measures onto the text shelf.",
    AuthLabelEditingDisabledShow: "In order to edit mark labels, check the \"Show Mark Labels\" checkbox.",
    AuthLeftContentPaneLabel: "Content",
    AuthLeftLayoutPaneLabel: "Layout",
    AuthLeftPaneLabelDashboard: "Dashboard",
    AuthLeftPaneTabLabelAnalytics: "Analytics",
    AuthLineAutomaticPreview: "Automatic",
    AuthLineOffPreview: "Off",
    AuthLineSizePixels: "{0} px",
    AuthMarkSizeLabel: "Mark Size",
    AuthMarksCardChooseField: "More Fields",
    AuthMarksCardEncodingTooltipBasic: "Drag dimensions or measures here.",
    AuthMarksCardEncodingTooltipOptions: "Drag dimensions or measures here, or click for more options.",
    AuthMastheadDone_Confirm_CanLogin: "Do you want to save your changes to the workbook? <br><br>You will need to sign in before you can finish saving your changes.",
    AuthMastheadDone_Confirm_CanLogin_Confirm: "Sign In and Save",
    AuthMastheadDone_Confirm_CanLogin_Confirm_Publish: "Sign In and Publish",
    AuthMastheadDone_Confirm_CanLogin_Deny: "Don\'t Save",
    AuthMastheadDone_Confirm_CanLogin_Deny_Publish: "Don\'t Publish",
    AuthMastheadDone_Confirm_CanLogin_Publish: "Do you want to publish your changes to the workbook? <br><br>You will need to sign in before you can finish publishing your changes.",
    AuthMastheadDone_Confirm_CanPublish: "Do you want to publish your changes to the workbook?",
    AuthMastheadDone_Confirm_CanPublishAs: "Do you want to publish your changes in a new workbook?",
    AuthMastheadDone_Confirm_CanPublishAs_Confirm: "Publish a Copy",
    AuthMastheadDone_Confirm_CanPublishAs_Deny: "Don\'t Publish",
    AuthMastheadDone_Confirm_CanPublish_Confirm: "Publish",
    AuthMastheadDone_Confirm_CanPublish_Deny: "Don\'t Publish",
    AuthMastheadDone_Confirm_CanSave: "Do you want to save your changes to the workbook?",
    AuthMastheadDone_Confirm_CanSaveAs: "Do you want to save your changes in a new workbook?",
    AuthMastheadDone_Confirm_CanSaveAs_Confirm: "Save a Copy",
    AuthMastheadDone_Confirm_CanSaveAs_Deny: "Don\'t Save",
    AuthMastheadDone_Confirm_CanSave_Confirm: "Save",
    AuthMastheadDone_Confirm_CanSave_Deny: "Don\'t Save",
    AuthMastheadDone_Confirm_CanSave_Metrics: "Do you want to save your metric?",
    AuthMastheadDone_Confirm_Datasource_Description: "Do you want to save your changes in a new datasource?",
    AuthMastheadDone_Confirm_Datasource_Title: "Save Datasource",
    AuthMastheadDone_Confirm_Title: "Save Workbook",
    AuthMastheadDone_Confirm_Title_Metrics: "Save Metric",
    AuthMastheadDone_Confirm_Title_Publish: "Publish Workbook",
    AuthMastheadHelp: "Help",
    AuthMastheadHelpSearch: "Search help",
    AuthMastheadLogin: "Sign In",
    AuthMastheadLogout: "Sign Out",
    AuthMastheadUserPrefs: "User Preferences",
    AuthMenuBarAnalysis: "Analysis",
    AuthMenuBarDashboard: "Dashboard",
    AuthMenuBarData: "Data",
    AuthMenuBarDraftIndicator: "Draft",
    AuthMenuBarExit: "Close",
    AuthMenuBarFile: "File",
    AuthMenuBarFormat: "Format",
    AuthMenuBarMap: "Map",
    AuthMenuBarPublishButtonMenuAriaLabel: "More publish options",
    AuthMenuBarPublishButtonPublish: "Publish",
    AuthMenuBarPublishButtonPublishAs: "Publish As...",
    AuthMenuBarStory: "Story",
    AuthMenuBarWindow: "Window",
    AuthMenuBarWorksheet: "Worksheet",
    AuthMetricsSaveTitle: "Save Metric",
    AuthNumberFormatDecimalLabel: "Decimal Places",
    AuthNumberFormatSeparatorLabel: "Include separators",
    AuthNumberFormatTypeAuto: "Automatic",
    AuthNumberFormatTypeCurrency: "Currency",
    AuthNumberFormatTypeLabel: "Number Type",
    AuthNumberFormatTypeNumber: "Number",
    AuthNumberFormatTypePercentage: "Percentage",
    AuthNumberFormatTypeScientific: "Scientific",
    AuthNumberFormatUnitsBillionsEnglish: "Billions (B)",
    AuthNumberFormatUnitsBillionsStandard: "Billions (G)",
    AuthNumberFormatUnitsLabel: "Units",
    AuthNumberFormatUnitsMillions: "Millions (M)",
    AuthNumberFormatUnitsNone: "None",
    AuthNumberFormatUnitsThousands: "Thousands (K)",
    AuthOffLabel: "OFF",
    AuthOnLabel: "ON",
    AuthPillRemove: "Remove",
    AuthPublishButtonPublish: "Publish",
    AuthPublishTitle: "Publish Workbook",
    AuthPublishUploadedFileDialogPublish: "The uploaded file is available in your editing session but will not be saved to your draft. Publish the workbook before you close the editor to save this file.",
    AuthPublishUploadedFileDialogTitle: "Save Your Uploaded File?",
    AuthRenameDataSource: "Rename Datasource",
    AuthRenameDatasourceAliasHeader: "Rename Data Source Alias",
    AuthRenameDatasourceError: "A data source with that name already exists. Try again using a different name.",
    AuthRenameDatasourceInfoMessage: "Adding an alias will not affect the original data source.",
    AuthRenameField: "Rename Field",
    AuthRenameObject: "Rename Table",
    AuthRenameSheet: "Rename Sheet",
    AuthRenameSheetError: "Please rename the sheet to a new unique name",
    AuthResetTooltip: "Reset Tooltip",
    AuthReverseColorLabel: "Reverse",
    AuthSaveButtonCancel: "Cancel",
    AuthSaveButtonSave: "Save",
    AuthSaveConfirmOverwrite: "{0} Overwrite it?",
    AuthSaveErrorTitle: "Error Saving",
    AuthSaveGoneDialogContentAutosaveOn: "Your changes are automatically saving to a private draft. Publish when you’re ready to share your changes with others.",
    AuthSaveGoneDialogContentExplainPublish: "Use Publish to save your work to a designated location.",
    AuthSaveGoneDialogContentNotPublished: "After you publish the first time, we will start to autosave your changes. Publish when you’re ready to share your changes with others.",
    AuthSaveGoneDialogTitleAfter: "Autosave is On",
    AuthSaveGoneDialogTitleBefore: "Where Did Save Go?",
    AuthSaveLabelEmbedPassword: "Embed password for data source",
    AuthSaveLabelLocation: "Location",
    AuthSaveLabelName: "Name",
    AuthSaveLabelProject: "Project",
    AuthSaveLabelSaveTo: "Save to",
    AuthSaveLabelShowTabs: "Show sheets as tabs",
    AuthSavePersonalSpaceTitle: "Personal Space",
    AuthSaveTitle: "Save Workbook",
    AuthSaveWorkbookAccessCurrent: "(current)",
    AuthSaveWorkbookAccessEmbed: "Embed my data source credentials",
    AuthSaveWorkbookAccessHeaderSimple: "Workbook Access",
    AuthSaveWorkbookAccessRequireCreds: "Require data source credentials to view workbook",
    AuthSaveWorkbookSavedMessage: "Workbook saved",
    AuthSchemaViewerHeaderData: "Data",
    AuthSchemaViewerHeaderDimensions: "Dimensions",
    AuthSchemaViewerHeaderFolders: "Folders",
    AuthSchemaViewerHeaderMeaures: "Measures",
    AuthSchemaViewerHeaderParameters: "Parameters",
    AuthSchemaViewerHeaderSets: "Sets",
    AuthSchemaViewerHeaderTables: "Tables",
    AuthSchemaViewerNoSearchMatches: "No matches",
    AuthSchemaViewerSearchPlaceholderText: "Search",
    AuthSchemaViewerSearchToggleButtonLabel: "Find Field",
    AuthShowMeApply: "Apply",
    AuthShowMeCantApply: "Can\'t Apply",
    AuthShowMeMultipleDimensions: "Dimensions",
    AuthShowMeMultipleMeasures: "Measures",
    AuthShowMeRecommended: "Recommended",
    AuthShowMeSingleDimension: "Dimension",
    AuthShowMeSingleMeasure: "Measure",
    AuthSteppedColorLabel: "Steps",
    AuthStepsLabel: "steps",
    AuthToolbarAddAllSubtotals: "Add All Subtotals",
    AuthToolbarCellSize: "Cell Size",
    AuthToolbarCellSizeBigger: "Bigger",
    AuthToolbarCellSizeNarrower: "Narrower",
    AuthToolbarCellSizeShorter: "Shorter",
    AuthToolbarCellSizeSmaller: "Smaller",
    AuthToolbarCellSizeTaller: "Taller",
    AuthToolbarCellSizeWider: "Wider",
    AuthToolbarCellTypeSquare: "Square",
    AuthToolbarCellTypeText: "Text",
    AuthToolbarDownloadWorkbook: "Workbook",
    AuthToolbarDownloadWorkbookErrorContent: "This workbook has unsaved changes. Save your changes and then try again.",
    AuthToolbarDownloadWorkbookErrorTitle: "Can\'t download workbook",
    AuthToolbarExport: "Download",
    AuthToolbarFont: "Font",
    AuthToolbarFontDecrease: "Decrease Font Size",
    AuthToolbarFontIncrease: "Increase Font Size",
    AuthToolbarFormatWorkbook: "Format Workbook",
    AuthToolbarMarkHideLabels: "Hide Labels",
    AuthToolbarMarkShowLabels: "Show Labels",
    AuthToolbarMore: "More",
    AuthToolbarOpenOnDesktopDisabledForPersonalSpaces: "To use Edit in Desktop, save the workbook outside of Personal Space",
    AuthToolbarOpenOnDesktopErrorContent: "This workbook has unsaved changes. Save your changes and try again.",
    AuthToolbarOpenOnDesktopErrorTitle: "Unable to Open in Tableau Desktop",
    AuthToolbarPauseUpdates: "Pause Updates",
    AuthToolbarRedo: "Redo",
    AuthToolbarRemoveAllSubtotals: "Remove All Subtotals",
    AuthToolbarResumeUpdates: "Resume Updates",
    AuthToolbarShare: "Share",
    AuthToolbarShowColumnGrandTotals: "Show Row Grand Totals",
    AuthToolbarShowMe: "Show Me",
    AuthToolbarShowRowGrandTotals: "Show Column Grand Totals",
    AuthToolbarSubscribe: "Subscribe",
    AuthToolbarSwap: "Swap",
    AuthToolbarTotals: "Totals",
    AuthToolbarUndo: "Undo",
    AuthToolbarWorksheet: "Worksheet",
    AuthToolbarZoomLevel: "Fit",
    AuthWorkbookFormatPaneClear: "Reset to Defaults",
    AuthWorkbookFormatPaneClearOne: "Clear",
    AuthWorkbookFormatPaneClearTooltip: "Resets the above workbook formatting to its default settings",
    AuthWorkbookFormatPaneCloseTooltip: "Close formatting pane",
    AuthWorkbookFormatPaneTitle: "Format workbook",
    AuthenticationRequired: "Authentication required",
    AuthorBylineText: "See more by this author",
    AuthoringAutoRecoveredSessionMessage: "Last edits recovered. To save all changes, click File > Save or Save As. To revert to the prior version, click File > Revert.",
    AuthoringAutoRecoveredSessionMessageNoPublish: "Last edits recovered. To revert to the prior version, click File > Revert.",
    AuthoringAutoRecoveredSessionMessageNoSave: "Last edits recovered. To save all changes, click File > Save As. To revert to the prior version, click File > Revert.",
    AuthoringAutoRecoveredSessionMessagePublish: "Last edits recovered. To save all changes, click File > Publish or Publish As. To revert to the prior version, click File > Revert.",
    AuthoringAutoRecoveredSessionMessagePublishAsNoPublish: "Last edits recovered. To save all changes, click File > Publish As. To revert to the prior version, click File > Revert.",
    AuthoringAutoRecoveredSessionMessagePublishNoPublishAs: "Last edits recovered. To save all changes, click File > Publish. To revert to the prior version, click File > Revert.",
    AuthoringAutoRecoveredSessionMessageSaveNoSaveAs: "Last edits recovered. To save all changes, click File > Save. To revert to the prior version, click File > Revert.",
    AuthoringLinePatternLabelDashed: "Dashed line",
    AuthoringLinePatternLabelDotted: "Dotted line",
    AuthoringLinePatternLabelSolid: "Solid line",
    AuthoringMenuBarCloseButtonLabel: "Close",
    AuthoringToastActionMessageGoToWorkbook: "Go to workbook",
    AuthoringToastMessagePublishedWorkbook: "\"{0}\" has been published",
    AuthoringToastMessagePublishedWorkbookToLocation: "\"{0}\" has been published to {1}",
    AuthoringWorkbookTitle: "Edit | {0}",
    AutoSaveAllChangesSaved: "All changes saved",
    AutoSaveJustPublished: "Just published",
    AutoSaveSavingInProgress: "Saving changes...",
    AutomaticDashboardSizeText: "The dashboard will resize to fit any screen it is displayed on",
    BaseClientAllAxisRanges: "All Axis Ranges",
    BaseClientAllChanges: "All Changes",
    BaseClientAllFilters: "All Filters",
    BaseClientAllSorts: "All Sorts",
    BaseClientColumns: "Columns",
    BaseClientInvalidSheet: "Unable to display view for the sheet \'{0}\'. The sheet is invalid.",
    BaseClientRows: "Rows",
    BaseClientSessionExpiredDialogMessage: "Your viewer session has expired. You must refresh your browser.",
    BaseClientSessionExpiredDialogTitle: "Session Expired",
    BigQueryUseLegacySQLLabel: "Use Legacy SQL",
    BinColumnTableName: "Bin",
    BrowserErrorProcessing: "Browser Processing Error",
    BrowserErrorProcessingMessage: "An error occurred processing the server response.",
    BrowserSecurityWarning: "Your connection through Internet Explorer is not secure. To continue, switch to a different browser or contact your IT Administrator.",
    CalcColumnTableName: "Calculation",
    CalcEditorApply: "Apply",
    CalcEditorApplyTooltip: "Apply(Ctrl+Enter)",
    CalcEditorApplyTooltipMac: "Apply(Cmd+Enter)",
    CalcEditorCalcError: "The calculation contains errors.",
    CalcEditorCalcOk: "The calculation is valid.",
    CalcEditorDependenciesPrefix: "Changes to this calculation might change the following:",
    CalcEditorOkButtonTooltip: "Apply and Close",
    Cancel: "Cancel",
    CancelDialogCancellingStatus: "Cancelling...",
    CancelDialogProcessingStatus: "Processing...",
    CannotSaveDataSourcePersonalSpaceContent: "Can\'t save data source to Personal Space. Move the workbook to another location to save the data source.",
    CannotSaveDataSourcePersonalSpaceTitle: "Unable to save data source",
    ChromeDropdownButtonTooltip: "More Options",
    ClearAliases: "Clear Aliases",
    ClearAllButtonText: "Clear List",
    CloseDataSourceErrorDialogEpilogue: "Make sure these sheets are no longer using the data source and then try again.",
    CloseDataSourceErrorDialogMessage: "The \'{0}\' data source cannot be closed because the following sheets are using it:",
    CloseDataSourceErrorDialogTitle: "Cannot close data source",
    CloudConnectionWaitDialogSubtitle: "This may take a few minutes",
    CloudConnectionWaitDialogSubtitleFilename: "Loading {0}. This may take a few minutes.",
    CloudConnectionWaitDialogTitle: "Connecting...",
    CollapseSchemaPane: "Collapse",
    CommentingToolbarButtonLabel: "Comments",
    ConfirmationButtonConfirm: "Yes",
    ConfirmationButtonDeny: "No",
    ConfirmationTitle: "Confirm",
    ConnectToCloudFileWindowTitle: "Connect to {0}",
    ConnectToData: "Connect to Data",
    ConnectToDialogErrorMessage: "Something went wrong and the Connect To dialog didn\'t load correctly. Try opening the dialog again.",
    ConnectionDialogSubtitleConnect: "Choose an existing data source to start from.",
    ConnectionDialogSubtitleCreateAndConnect: "Connect to the data you need to visualize.",
    ConnectionDialogSubtitleCreateNewConnection: "Add a new connection to create cross-database joins.",
    ConnectionMissingFileDialogMissingDirectoryText: "The directory is missing or has been moved:<br>{0}<br>Replace it with another file?",
    ConnectionMissingFileDialogText: "Could not find the referenced file: {0}.<br>Replace it with another file?",
    ConnectionMissingFileDialogTitle: "Missing file",
    ConnectorDetailBackButton: "Back",
    CreateAreaAnnotationFromVizContextMenu: "Annotate Area...",
    CreateConnectionBadPasswordError: "The username or password is not valid.  Check the database name and credentials and try again.",
    CreateConnectionErrorHeader: "Can’t connect to {0}",
    CreateConnectionExcelAndText: "Excel and text",
    CreateConnectionOnTableauServer: "On This Site",
    CreateConnectionPublishedDatasources: "Published data sources",
    CreateConnectionToAFile: "Files",
    CreateConnectionToDataMarketplace: "Data Repository (Beta)",
    CreateConnectionToDataMarketplaceErrorMessage: "Error Loading the Data Repository (Beta) Dataset",
    CreateConnectionToDatabase: "Connectors",
    CreateMapLayersMenuItem: "Map Layers...",
    CreateMapOptionsMenuItem: "Map Options...",
    CreateMarkAnnotationFromVizContextMenu: "Annotate Mark...",
    CreatePointAnnotationFromVizContextMenu: "Annotate Point...",
    CredentialNotEmbedded: "credential is not embedded for the workbook",
    CurrentPagePanelNextPage: "Next Page",
    CurrentPagePanelPlayForward: "Play Forward",
    CurrentPagePanelPlayReverse: "Play Reverse",
    CurrentPagePanelPreviousPage: "Previous Page",
    CurrentPagePanelShowHistory: "Show history",
    CurrentPagePanelStop: "Stop",
    CurrentSubscribers: "Current Subscribers",
    CustomPaletteGroupUnselectedNote: "A custom palette is selected. If you select a different palette you won’t be able to select this custom palette for this view again.",
    CustomViewsAddYourOwnCustomView: "Add your own custom view",
    CustomViewsCancel: "Cancel",
    CustomViewsCannotChangeDefault: "Cannot change default to an unlisted custom view",
    CustomViewsChangeDefaultTo: "Change default to \"{0}\"",
    CustomViewsCurrentDefaultIs: "Current default is \"{0}\"",
    CustomViewsDialogTitle: "Custom Views",
    CustomViewsDone: "Done",
    CustomViewsManageCustomViews: "Manage Custom Views",
    CustomViewsManageHeader: "Advertise, rename, and delete my custom views",
    CustomViewsMyCustomViews: "My Custom Views",
    CustomViewsNameYourCustomView: "Name your custom view",
    CustomViewsOriginalName: "Original Name: \"{0}\"",
    CustomViewsOriginalView: "Original",
    CustomViewsOtherCustomViews: "Other Custom Views",
    CustomViewsRemember: "Remember",
    CustomViewsRememberMyChanges: "Remember my changes",
    CustomViewsSelectCustomView: "Select Custom View",
    CustomViewsStartManage: "Manage Custom Views",
    CustomViewsUndo: "Undo",
    CustomViewsUnlistedCustomView: "Unlisted Custom View",
    DashboardAuthZoneHeightDisplay: "h {0}",
    DashboardAuthZoneLeftPositionDisplay: "x {0}",
    DashboardAuthZoneTopPositionDisplay: "y {0}",
    DashboardAuthZoneWidthDisplay: "w {0}",
    DashboardAuthoringAutoGenerateLayoutTooltip: "Click to auto-generate layout",
    DashboardAuthoringCustomSizeName: "Custom",
    DashboardAuthoringCustomizeLayoutTooltip: "Click to edit layout",
    DashboardAuthoringDeviceLayoutDefault: "Default",
    DashboardAuthoringDeviceLayoutDesktop: "Desktop",
    DashboardAuthoringDeviceLayoutPhone: "Phone",
    DashboardAuthoringDeviceLayoutTablet: "Tablet",
    DashboardAuthoringHeightSpinnerLabel: "Height",
    DashboardAuthoringMaximumSizeLabel: "Maximum",
    DashboardAuthoringMinimumSizeLabel: "Minimum",
    DashboardAuthoringSizePopupTitle: "Dashboard Size",
    DashboardAuthoringSizeRadioAriaLabel: "Size Radio Button Group",
    DashboardAuthoringWidthSpinnerLabel: "Width",
    DashboardButtonAccessDenied: "Access Denied",
    DashboardGridSize: "Grid Size (px)",
    DashboardLayoutClearAll: "Clear All",
    DashboardLayoutGroup: "Group",
    DashboardLayoutRemoveFromGroup: "Remove From Group",
    DashboardLayoutUngroup: "Ungroup",
    DashboardSizeSupressedExceptionMessage: "No pixel dimensions were received. To resolve the issue, refresh the browser, or try again later.",
    DashboardSpacingNone: "None",
    DataAccelerationDisableFailureToast: "Failed to turn off acceleration for the view.",
    DataAccelerationDisableSuccessToast: "Turned off acceleration for the view.",
    DataAccelerationEnableFailureToast: "Failed to turn on acceleration for the view.",
    DataAccelerationEnableSuccessToast: "Turned on acceleration for the view.",
    DataAccelerationFailureToast_MissingCredential: "Failed to perform the action due to credential is not embedded in the workbook.",
    DataAccelerationFailureToast_UserNoPermission: "Failed to perform the action due to user has no permission.",
    DataAlertAccessErrorMessage: "The view \"{0}\" has changed, and the alert you are trying to access is no longer valid.",
    DataAlertAccessErrorTitle: "Error Accessing Alert",
    DataAlertAddMeFailureToast: "Unable to add you to recipients for this alert.",
    DataAlertAddMeInvalidEmailAddressFailureToast: "Unable to add you to recipients for this alert. To receive alerts, add an email address to your Tableau account settings.",
    DataAlertAddMeSuccessToast: "You\'ve been added to \"{0}\".",
    DataAlertChangeOwnerFailureToast: "Could not change owner on this alert.",
    DataAlertChangeOwnerSuccessToast: "The owner of the alert has been changed.",
    DataAlertCondition: "Condition",
    DataAlertCreateButton: "Create Alert",
    DataAlertCreateButtonSaving: "Saving...",
    DataAlertCreateFailure: "Failed to create an alert.",
    DataAlertCreateSuccess: "Alert successfully created.",
    DataAlertDatasourceError: "Unable to create alert because there was an error connecting to the data source. Check your data source credentials and try again.",
    DataAlertDeleteButtonResumeError: "Delete Alert",
    DataAlertDeleteConfirmation: "Permanently delete the alert \"{0}\"? This alert has {1} recipients.",
    DataAlertDeleteConfirmationToast: "\"{0}\" was deleted.",
    DataAlertDeleteFailureToast: "Could not delete this alert.",
    DataAlertDialogTitle: "Create Alert",
    DataAlertDialogTitleEditMode: "Edit Alert",
    DataAlertDisplayAlertFailureToast: "Failed to display alert \"{0}\".",
    DataAlertEditFailureToast: "Could not edit this alert.",
    DataAlertErrorDialogTitle: "Error Editing Alert",
    DataAlertErrorDialogViewChanged: "The view \"{0}\" has changed, and the alert you are trying to edit is no longer valid.",
    DataAlertErrorDialogViewChangedWithSubject: "The view \"{0}\" has changed, and the alert \"{1}\" is no longer valid.",
    DataAlertInitFailure: "Alert creation dialog could not be generated.",
    DataAlertInvalidPluralUsers: "{0} users cannot be alerted.",
    DataAlertInvalidUser: "1 user cannot be alerted.",
    DataAlertLoadCustomizedViewFailure: "Unable to load customized view",
    DataAlertLoadForEditFailure: "Could not load data alert for editing.",
    DataAlertNoSubjectErrorMessage: "Enter a subject for alert emails",
    DataAlertNoUsersMatchSearch: "No users match this search",
    DataAlertNotificationInterval: "When the condition is true, send alert:",
    DataAlertOnConstantThreshold: "Send alert if \'{0}\' is:",
    DataAlertPublicCheckboxLabel: "Make visible to others",
    DataAlertPublicInfo: "Anyone with access to the view can see and add themselves to this alert.",
    DataAlertRecipientPillNoDownloadPermissions: "{0} doesn’t have permission to download.",
    DataAlertRecipientPillNoEmail: "{0} doesn’t have a valid email address in Tableau.",
    DataAlertRecipientPillNoViewPermissions: "{0} doesn’t have permissions to view.",
    DataAlertRecipientPillUnlicensed: "{0} is an unlicensed user and doesn’t have permission to view.",
    DataAlertRecipientWithNoEmail: "Users must have email addresses in Tableau before you can add them as recipients",
    DataAlertRecipients: "Recipients",
    DataAlertRemoveMeFailureToast: "Unable to remove you from recipients for this alert.",
    DataAlertRemoveMeSuccessToast: "You\'ve been removed from {0}",
    DataAlertResumeErrorDialogTitle: "Error Resuming Alert",
    DataAlertResumedFailureToast: "Data alert failed to resume",
    DataAlertResumedSucessfullyToast: "Data alert resumed successfully",
    DataAlertShowFailureToast: "Unable to access this alert.",
    DataAlertSubject: "Subject",
    DataAlertSubjectTemplate: "Data alert - {0}",
    DataAlertThreshold: "Threshold",
    DataAlertThresholdConditionMet: "Condition currently true",
    DataAlertThresholdConditionUnmet: "Condition not currently true",
    DataAlertThresholdErrorDouble: "Value must be a number",
    DataAlertThresholdErrorGeneric: "Value must be a number",
    DataAlertThresholdErrorIntegerInputDouble: "Value can’t include a decimal",
    DataAlertThresholdErrorIntegerInputNonNumeric: "Value must be a whole number",
    DataAlertToolbarButtonLabel: "Alerts",
    DataAlertUpdateButton: "Save Alert",
    DataAlertUpdateFailure: "Failed to update alert.",
    DataAlertUpdateSuccess: "Alert successfully updated.",
    DataAlertsRecipientsSearchPlaceholder: "Recipient name or username",
    DataCatalogSevereWarningAction: "Open Data Details",
    DataCatalogSevereWarningCount: "Important data quality warnings affect this view.",
    DataDetailsToolbarButtonLabel: "Data Details",
    DataGridCancelButton: "Cancel",
    DataGridErrorButton: "Dismiss",
    DataGridErrorText: "An error occurred.",
    DataGridLoadingText: "Loading data...",
    DataGridNullKeyword: "null",
    DataGridUndefinedKeyword: "Undefined",
    DataGridUpdateButton: "Update Now",
    DataGridZeroRowsText: "No data",
    DataInterpreterDataLoss: "Data Interpreter removed some data.",
    DataInterpreterDescription: "Data Interpreter may be able to clean your {0} workbook.",
    DataInterpreterFinished: "Cleaned with Data Interpreter",
    DataInterpreterLoading: "Loading...",
    DataInterpreterReady: "Use Data Interpreter",
    DataInterpreterUndo: "To undo changes, clear the check box.",
    DataLineageToolbarButtonLabel: "Lineage",
    DataMonitoringToolbarButtonLabel: "Data Changes",
    DataSourceConnectionDriverNotInstalledErrorMessage: "The driver required to connect to the data source isn\'t installed. Contact your Tableau Server Administrator.",
    DataSourceConnectionErrorMessage: "An error occurred when connecting to your data source. The data source might be corrupt or not valid.",
    DataSourceConnectionErrorTitle: "Unable to connect to data source",
    DataSourceConnectionErrorTitleText: "There was a problem connecting to the data source \"{0}\". Try editing the data source.",
    DataSourceCreationInProgress: "Data source creation in progress",
    DataSourceGenericErrorButtonLabel: "Try Again",
    DataSourceGenericErrorMsg: "Unable to proceed because of an error from the data source.",
    DataSourceGenericErrorSubMsg: "Try connecting again. If the problem persists, disconnect from the data source and contact the data source owner.",
    DataSourceGenericTitle: "Data Source Error",
    DataTabAddConnectionToDatasource: "Add",
    DataTabCloseConnection: "Remove",
    DataTabConnectionsHeader: "Connections",
    DataTabCreateJoinCalculation: "Create Join Calculation...",
    DataTabCustomSqlTitle: "Custom SQL",
    DataTabDataGridButtonTooltip: "Preview data source",
    DataTabEditConnection: "Edit Connection...",
    DataTabEditDialogTitle: "Join",
    DataTabEditJoinAddJoinPlaceholder: "Add new join clause",
    DataTabEditJoinCalculation: "Edit Join Calculation...",
    DataTabEditJoinClauseHeaderTitle: "Data Source",
    DataTabEditJoinClauseRemoveTooltip: "Remove join clause",
    DataTabEditJoinDisabledTooltip: "This join type is not available for this connection.",
    DataTabEditJoinFull: "Full Outer",
    DataTabEditJoinFullTooltip: "Includes all values from both tables. Members without matches show up as null.",
    DataTabEditJoinInner: "Inner",
    DataTabEditJoinInnerTooltip: "Includes only values with matches in both tables.",
    DataTabEditJoinLeft: "Left",
    DataTabEditJoinLeftTooltip: "Includes all members in left table and all matches from right table. Members without matches will show up as nulls on the right.",
    DataTabEditJoinRight: "Right",
    DataTabEditJoinRightTooltip: "Includes all members in right table and all matches from left table. Members without matches will show up as nulls on the left.",
    DataTabExtractCreationSuccessToast: "Extract creation is complete.",
    DataTabExtractRefreshSuccessToast: "Extract refresh is complete.",
    DataTabFilePropertiesCharset: "Character set:",
    DataTabFilePropertiesLocale: "Locale:",
    DataTabFilePropertiesQualifier: "Text qualifier:",
    DataTabFilePropertiesSeparator: "Field separator:",
    DataTabFilterInfoLabel: "Filters",
    DataTabInitialSql: "Initial SQL...",
    DataTabJoinOnCalculationCaption: "Join Calculation",
    DataTabLiveExtractLabel: "Connection",
    DataTabMetadataGridButtonTooltip: "Manage metadata",
    DataTabName: "Data Source",
    DataTabNewCustomSqlLabel: "New Custom SQL",
    DataTabNewCustomSqlTooltip: "Create new custom SQL query",
    DataTabNewUnionLabel: "New Union",
    DataTabNewUnionTooltip: "Add new union",
    DataTabQualifierAutomatic: "Automatic",
    DataTabQualifierNone: "None",
    DataTabRelationshipCalculationCaption: "Relationship Calculation",
    DataTabRenameConnection: "Rename",
    DataTabRenameConnectionTitle: "Rename Connection",
    DataTabSchemaReadOnlyNoneSelected: "No {0} selected.",
    DataTabSchemaSlowMetadataNoneSelected: "Select {0}",
    DataTabSearchContains: "Contains",
    DataTabSearchCountEntityNoMatch: "No matches",
    DataTabSearchCountEntityResult: "Found {0} matches",
    DataTabSearchEntityCheckPermissions: "Check permissions",
    DataTabSearchEntityCountLoading: "Counting...",
    DataTabSearchEntityFetchLoading: "Fetching results....",
    DataTabSearchEntityLoadButton: "Load",
    DataTabSearchExact: "Exact",
    DataTabSearchFilter: "Search",
    DataTabSearchStartsWith: "Starts with",
    DataTabSeparatorComma: "Comma",
    DataTabSeparatorOther: "Other",
    DataTabSeparatorSemicolon: "Semicolon",
    DataTabSeparatorSpace: "Space",
    DataTabSeparatorTab: "Tab",
    DataTabSeparatorVerticalBar: "Vertical Bar",
    DataTabStoredProceduresHeader: "Stored Procedures",
    DataTabStoredProceduresNotAllowed: "Stored procedures are not available for multi-connection data sources.",
    DataTabStoredProceduresPlaceHolder: "Enter stored procedure name",
    DataTabStoredProceduresWithParamsNotAvailable: "You can’t run a stored procedure that contains a parameter.",
    DataTabStoredProceduresWithParamsNotAvailableTitle: "Unable to run",
    DataTabUnionApplyLabel: "Apply",
    DataTabUnionConnectionNameLabel: "Connection: ",
    DataTabUnionDifferentConnectionWarning: "You can only union data from the same connection",
    DataTabUnionDragRegionLabel: "Drag table to union",
    DataTabUnionDragTables: "Drag tables here",
    DataTabUnionInvalidPillTooltip: "Tableau can\'t find or recognize this table. Remove or replace the table",
    DataTabUnionOKLabel: "OK",
    DataTabUnionTablesLabel: "Tables in union: ",
    DataTabUnionUnsupported: "Only the first table in your selection will be added because union is not available for this database.",
    DataTabViewDataCancel: "Cancel",
    DataTabViewDataCanceling: "Cancelling...",
    DataTabViewDataDialogTitle: "View Data: {0}",
    DataTabViewDataGetDataButtonTooltip: "Get data",
    DataTabViewDataLoadingRows: "Loading rows...",
    DataTabViewDataProcessingRows: "Processing rows...",
    DataTabViewDataTooltip: "View data",
    December: "December",
    DecemberNarrow: "D",
    DecemberShort: "Dec",
    DeleteAnnotationFromVizContextMenu: "Delete Annotation",
    DeleteSelectedAnnotationFromVizContextMenu: "Delete Selected Annotations",
    DeleteSheetWithVizInTooltipDialogButton: "Delete Worksheet",
    DeleteSheetWithVizInTooltipDialogMessage: "This worksheet is displayed in the tooltips of other worksheets. Deleting this worksheet will also remove it from those tooltips.<br><br>Are you sure you want to delete it?",
    DeleteSheetWithVizInTooltipDialogTitle: "Delete Worksheet",
    DeviceLayoutDefaultMessagePart1: "The content and layout of the dashboard on all devices will match the Default dashboard.",
    DeviceLayoutDefaultMessagePart2: "Click \"Custom\" to change how the dashboard will look for the device.",
    DeviceLayoutSelectorConfirmPromptDesktopLayoutMessage: "Switch to desktop layout?",
    DeviceLayoutSelectorConfirmPromptPhoneLayoutMessage: "Switch to phone layout?",
    DeviceLayoutSelectorConfirmPromptTabletLayoutMessage: "Switch to tablet layout?",
    DeviceLayoutSelectorConfirmPromptTitle: "Change Device Layout",
    DeviceLayoutSelectorDesktopLayoutToolbarButtonLabel: "Desktop Layout",
    DeviceLayoutSelectorPhoneLayoutToolbarButtonLabel: "Phone Layout",
    DeviceLayoutSelectorTabletLayoutToolbarButtonLabel: "Tablet Layout",
    DeviceLayoutTableauMobileApp: "Tableau Mobile App",
    DeviceLayoutTableauMobileAppTooltip: "Adjusts the preview frame to show available screen size for devices running Tableau Mobile",
    DeviceModel: "Model",
    DevicePreview: "Device Preview",
    DevicePreviewOffTooltip: "Turn off device preview",
    DevicePreviewTooltip: "Preview this dashboard on different devices",
    DeviceType: "Device Type",
    DialogButtonCancel: "Cancel",
    DialogButtonDownload: "Download",
    DialogButtonExport: "Generate",
    DialogButtonNext: "Next",
    DialogButtonOK: "OK",
    DialogButtonReset: "Reset to original field name",
    DialogNoButtonText: "No",
    DialogYesButtonText: "Yes",
    DisabledDataTabTooltipDetails: "Select another data source or download and then open this workbook using Tableau Desktop.",
    DisabledDataTabTooltipInfo: "The current data source can\'t be viewed from the data source page.",
    DiscoverToolbarButtonLabel: "Related Views",
    DownloadAsVersionDialogDownloadButton: "Download",
    DownloadAsVersionDialogHelpLink: "Learn more",
    DownloadAsVersionDialogTitle: "Download Tableau Workbook",
    DownloadAsVersionDialogWarning: "Select a version to download the workbook as. Keep the workbook in its current version or select a different version. If you downgrade the workbook to a previous version, some functionality may be lost.",
    DownloadAsVersionDropdownDefaultLabel: "Current",
    DownloadAsVersionDropdownLabel: "Version",
    DownloadDialogDownloadAsVersionButton: "Download As Version",
    DragAndDropAFileOrUploadFromComputer_Part1: "Drag and drop a file",
    DragAndDropAFileOrUploadFromComputer_Part2: "or",
    DragAndDropAFileOrUploadFromComputer_Part3: "Upload from computer",
    DragAndDropError_Multi: "Uploading multiple files is not allowed. Try again by uploading a single file instead.",
    DragAndDropError_Title: "Can\'t Upload Files",
    DropFieldHintText: "Drop field here",
    EditAnnotationFromVizContextMenu: "Edit Annotation",
    EditConnectionDialogTitle: "Edit Connection",
    EditConnectionInformationDialogText: "There was a problem connecting to the data source \"{0}\".<br>Would you like to edit the connection information?",
    EditConnectionInformationDialogTitle: "Edit connection",
    EditDataExplanation: "Select a published data source to edit it.",
    EditDatasourceLinkDisabledTooltip: "You cannot edit this data source because you only have permission to view the data source.",
    EditDatasourceLinkLabel: "Edit",
    EmptyDashboardMessage: "Add sheets here",
    EmptyDashboardSubMessage: "Drag and drop or double-click from the list on the left.",
    EmptyFloatingLayoutFlowMessage: "Hold down Shift to drop floating objects into this container",
    EmptyImageZoneMessage: "Choose an image using the object menu.",
    EmptyLayer: "Empty Layer",
    EmptyLayoutGridMessage: "Drag objects into this container, or hold down Shift to float them above.",
    EmptyLayoutStackMessage: "Drag objects into this container, or hold down Shift to float them above.",
    EmptyTextRegionMessage: "Double click to add or edit text.",
    EnterFullscreen: "Full Screen",
    ExitFullscreen: "Exit Full Screen",
    ExpandSchemaPane: "Expand",
    ExportCrosstabDialogMessage: "The crosstab is ready to download.",
    ExportCrosstabDialogTitle: "Download Crosstab",
    ExportCrosstabToExeclOnStoryWithJsApiErrorMessage: "Tableau JavaScript API does not support crosstab to Excel downloads on embedded stories. Try downloading crosstab to CSV.",
    ExportCrosstabToExeclOnStoryWithJsApiErrorTitle: "Download to Crosstab Error",
    ExportDataDialogMessage: "The data file is ready to download.",
    ExportDataDialogTitle: "Download Data",
    ExportFileConfirmationDialogMessage: "The file is ready to download.",
    ExportFileConfirmationDialogTitle: "Download File",
    ExportImageDialogMessage: "The image is ready to download.",
    ExportImageDialogTitle: "Download Image",
    ExportPowerPointDialogMessage: "The PowerPoint is ready to download.",
    ExportPowerPointDialogTitle: "Download PowerPoint",
    ExtensionBlockedByServer: "The server administrator placed the extension ({0}, {1}) on the block list to prevent the extension from running. Contact your server administrator for more information.",
    ExtensionBlockedPreRelease: "Version {0} of {1} is using a pre-release version of the Tableau Extensions API. Extensions using pre-released versions of the Tableau Extensions API are only supported on pre-release versions of Tableau. To obtain a version of this extension that works with a released version of Tableau, contact the extension developer at {2}.",
    ExtensionDeniedByUser: "This extension does not have permission to run. To grant approval, reset permissions by refreshing the page.",
    ExtensionDeniedByUserAuthoring: "This extension does not have permission to run. To grant approval, choose Reset Permissions in the More Options context menu.",
    ExtensionDisabledOnNewWorkbook: "You must save this workbook before the {0} extension can be used. Please save the workbook and try again.",
    ExtensionNotFoundOnSafelist: "The {0} extension (url: {1}) is not on the safe list for this site, and is therefore not allowed to run. Contact your {2} to add this extension to the safe list.",
    ExtensionNotSupportedOnPublic: "Extension {0} Version {1} isn\'t currently supported on Tableau Public.",
    ExtensionRequiresAuthorization: "{0}<br><br>The extension {0} requires authorization to run. The authorization page could take a few moments to appear. If you need to authorize the extension again, reload the page in your browser.<br><br>For more information about {0} visit: {1}.",
    ExtensionViolatesSafelistPermission: "The {0} extension (url: {1}) requires access to full data but has not been granted full data access in the site settings. Contact your {2} to change the data access setting for the extension.",
    ExtensionViolatesSafelistPermissionOnPublic: "The {0} extension (url: {1}) requires access to full data, but hasn\'t been granted full data access in the site settings.",
    ExtensionsDisabledOnPublic: "Extensions aren\'t currently supported on Tableau Public.",
    ExtensionsDisabledOnServer: "Extensions are not allowed on this server. Contact your server administrator to change this setting to allow extensions.",
    ExtensionsDisabledOnSite: "Extensions are not allowed on this site. Contact your {0} to change this site setting to allow extensions.",
    ExtractErrorTitle: "Error",
    ExtractInternalErrorMessage: "Internal error.",
    February: "February",
    FebruaryNarrow: "F",
    FebruaryShort: "Feb",
    FieldNameLabel: "Field Name:",
    FieldNameResetErrorMessage: "\"{0}\" cannot be reset to its default ({1}) name because another field in the workbook now has that name.",
    FieldNameResetErrorTitle: "Can\'t Reset the Field Name",
    FieldRenameError: "A field named \"{0}\" already exists.",
    FieldRenameErrorDialogTitle: "Can\'t Rename the Field",
    FileSingleUploadTitle: "Uploading File",
    FileUploadAccessError: "Can\'t access the file as it might be open or locked for editing. Close the file and then try again.",
    FileUploadAccessError_Title: "Can\'t open file",
    FileUploadButtonAdd: "Add",
    FileUploadButtonCancel: "Cancel",
    FileUploadButtonClose: "Close",
    FileUploadButtonLess: "Less",
    FileUploadButtonMore: "More",
    FileUploadButtonReplaceUpdate: "Replace and Update",
    FileUploadButtonRetry: "Retry",
    FileUploadButtonSkipPlural: "Skip Files and Start Uploading",
    FileUploadButtonSkipSingular: "Skip File and Start Uploading",
    FileUploadConnectionCreationErrorReason: "The connection couldn\'t be created from the uploaded file. Upload a different file and then try again.",
    FileUploadConnectionCreationErrorTitle: "Couldn\'t connect to uploaded file",
    FileUploadConnectionCreationMultiErrorTitle: "Couldn\'t connect to some uploaded files",
    FileUploadDSCreationErrorReason: "The datasource couldn\'t be created from the uploaded file. Upload a different file and then try again.",
    FileUploadDSCreationErrorTitle: "The datasource wasn\'t created",
    FileUploadDSErrorTitleMultiFailed: "Datasource Error",
    FileUploadDropToUploadInstructions: "Drop to upload",
    FileUploadErrorInfosCompletedHeader: "Completed",
    FileUploadErrorInfosFailedHeader: "Failed",
    FileUploadErrorTitle: "Upload Failed",
    FileUploadErrorTitleMultiComplete: "Upload Complete: {0}",
    FileUploadErrorTitleMultiFailed: "Upload Failed: {0}",
    FileUploadFailureIgnoreAndContinueLabel: "Ignore and Continue",
    FileUploadFailureTextPlural: "Upload of {0} files failed",
    FileUploadFailureTextSingular: "Upload of {0} failed",
    FileUploadFatalErrorFileExists: "The file you\'re uploading has the same file name as one currently in use. Do you want to replace and update the existing file, or add this file with a new name?",
    FileUploadFatalErrorFileIsEmptySubtitle: "This file is empty. Try again using a different file.",
    FileUploadFatalErrorFileIsTooBigSubtitle: "File too large. Maximum size: {0}",
    FileUploadFatalErrorSameFileTitle: "Same File Name",
    FileUploadFatalErrorTitle: "Can\'t Upload Files",
    FileUploadFatalErrorUnsupportedFileTypeByConnectionSubtitle_a_a: "A {0} can\'t be replaced by a {1}. Try again by uploading a {0} instead.",
    FileUploadFatalErrorUnsupportedFileTypeByConnectionSubtitle_a_an: "A {0} can\'t be replaced by an {1}. Try again by uploading a {0} instead.",
    FileUploadFatalErrorUnsupportedFileTypeByConnectionSubtitle_an_a: "An {0} can\'t be replaced by a {1}. Try again by uploading an {0} instead.",
    FileUploadFatalErrorUnsupportedFileTypeByConnectionSubtitle_an_an: "An {0} can\'t be replaced by an {1}. Try again by uploading an {0} instead.",
    FileUploadFatalErrorUnsupportedFileTypeSubtitle: "This file type is currently not supported on the web. To use this type of file, connect to it from Tableau Desktop and then publish it to the server.",
    FileUploadFileTypeAccess: "Access",
    FileUploadFileTypeExcel: "Excel",
    FileUploadFileTypeExcelFile: "Excel file",
    FileUploadFileTypeJson: "JSON file",
    FileUploadFileTypeOther: "Other file",
    FileUploadFileTypeSpatial: "Spatial file",
    FileUploadFileTypeStatistical: "Statistical file",
    FileUploadFileTypeText: "Text file",
    FileUploadFinishedTitle: "Done",
    FileUploadPreProcessingTitle: "Preparing files",
    FileUploadProcessingTitle: "Processing {0} Files",
    FileUploadProgressDialogTitle: "File Upload Progress",
    FileUploadProgressIndicator: "{0} {2} of {1} {2} uploaded",
    FileUploadServerUnresponsive: "No response from the server",
    FileUploadTitle: "Uploading {0} Files",
    FileUploadUploadErrorReason: "The file wasn\'t uploaded.",
    Filter: "Filter",
    FindAllButtonLabel: "Find All",
    FindContains: "Contains",
    FindExactMatch: "Exact Match",
    FindInRangeAll: "(All)",
    FindInRangeLabel: "Find in:",
    FindLabel: "Find:",
    FindNextButtonLabel: "Find Next",
    FindStartsWith: "Starts With",
    FindTextPlaceHolder: "Search",
    FirstEnding: "{0}st",
    FloatingZoomToolbarLayerControlTooltip: "Control Map Layers",
    FormatAnimationsSidePaneTitle: "Format Animations...",
    FormatWorksheetContextMenu: "Format Worksheet...",
    Friday: "Friday",
    FridayNarrow: "F",
    FridayShort: "Fri",
    FullViewDataCaption: "Full Data",
    FunctionTypeAggregate: "Aggregate",
    FunctionTypeAll: "All",
    FunctionTypeClearTooltip: "Clear",
    FunctionTypeDate: "Date",
    FunctionTypeLogical: "Logical",
    FunctionTypeNumber: "Number",
    FunctionTypeSearchHint: "Search",
    FunctionTypeSpatial: "Spatial",
    FunctionTypeString: "String",
    FunctionTypeTableCalculation: "Table Calculation",
    FunctionTypeType: "Type",
    FunctionTypeUser: "User",
    GlassPaneLoading: "Loading...",
    GlassPaneSessionExpired: "Session Expired",
    GlassPaneUpdating: "Updating...",
    GoToAccountSettings: "Go to Account Settings",
    GoToSheet: "Go to Sheet",
    GotoMyLocationPermissionDeniedError: "Tableau does not have permission to use your location. Check your location settings and try again.",
    GotoMyLocationPermissionDeniedUnsecureConnection: "Tableau does not have permission to use your location. Check your location settings and verify you are using a secure (https) connection.",
    GotoMyLocationPositionUnavailableError: "Tableau is unable to find your location. Check your internet connection and try again.",
    GotoMyLocationTimeoutError: "Our attempt to find your location timed out.",
    GotoMyLocationTooltip: "Go To My Location",
    GridDialogTitle: "Grid Options",
    GroupColumnTableName: "Group",
    GroupDialogGroupButtonLabel: "Group",
    GroupDialogHideFindOptions: "Hide Options",
    GroupDialogLargeDomainWarning: "Grouping functionality is disabled due to the large domain size of this column.",
    GroupDialogRenameButtonLabel: "Rename",
    GroupDialogShowFindOptions: "Show Options",
    GroupDialogUngroupButtonLabel: "Ungroup",
    GroupsLabel: "Groups:",
    HelpMenuItemAllHelpTopics: "Open Installed Help",
    HelpMenuItemContactSupport: "Support",
    HelpMenuItemGetHelpAndSupport: "Get Help & Support",
    HelpMenuItemWebAuthor: "Web Authoring Help",
    HelpMenuItemWebAuthor1: "Who can edit and create workbooks",
    HelpMenuItemWebAuthor2: "Edit and create views",
    HelpMenuItemWebAuthor3: "Create a workbook and build a view",
    HelpMenuItemWebDataSource: "Web Data Source Help",
    HideDetailsLabel: "Hide details",
    Hour: "hour",
    Hours: "{0} hours",
    IncludeOtherLabel: "Include \'Other\'",
    January: "January",
    JanuaryNarrow: "J",
    JanuaryShort: "Jan",
    July: "July",
    JulyNarrow: "J",
    JulyShort: "Jul",
    June: "June",
    JuneNarrow: "J",
    JuneShort: "Jun",
    LastPublished: "Last Published",
    LayoutPaneArrangeSectionTitle: "Arrange",
    LayoutPaneBackgroundColorTitle: "Background",
    LayoutPaneBorderButtonTitle: "Border",
    LayoutPaneFloatingCheckbox: "Floating",
    LayoutPaneHSizeSpinner: "Height",
    LayoutPaneMarginButtonTitle: "Outer Padding",
    LayoutPanePaddingButtonTitle: "Inner Padding",
    LayoutPaneSelectedItemTitle: "Selected Item",
    LayoutPaneSpacingAllSidesEqual: "All sides equal",
    LayoutPaneSpacingBottom: "Bottom",
    LayoutPaneSpacingLeft: "Left",
    LayoutPaneSpacingRight: "Right",
    LayoutPaneSpacingTop: "Top",
    LayoutPaneWSizeSpinner: "Width",
    LayoutPaneXPositionSpinner: "X",
    LayoutPaneYPositionSpinner: "Y",
    LayoutPaneZoneTitleCheckbox: "Show Title",
    LayoutToggleOptionCustom: "Custom",
    LayoutToggleOptionDefault: "Default",
    LayoutTreeSectionTitle: "Item hierarchy",
    LeftPaneAutoGeneratedPhoneLayoutWarningMsg: "This phone layout has been automatically generated. Device layouts cannot be edited on the web. To edit, open the workbook in Tableau Desktop.",
    LeftPaneDSDWarningMsg: "Device layouts cannot be edited on the web. To edit, open the workbook in Tableau Desktop.",
    LegacyPaletteUnselectedNote: "This palette is discontinued. If you select a different palette, you won’t be able to select this palette again.",
    Legend: "Legend",
    LegendPanelHighlightSelectedItems: "Highlight Selected Items",
    LinePatternNone: "None",
    LineTypeHeading: "Line Type",
    ListLengthFive: "{0}, {1}, {2}, {3}, and {4}",
    ListLengthFour: "{0}, {1}, {2}, and {3}",
    ListLengthSeven: "{0}, {1}, {2}, {3}, {4}, {5}, and {6}",
    ListLengthSix: "{0}, {1}, {2}, {3}, {4}, and {5}",
    ListLengthThree: "{0}, {1}, and {2}",
    ListLengthTwo: "{0} and {1}",
    LogOnButton: "Sign In to Continue",
    ManageCustomViewsDisabledExplanation: "There are no custom views to manage.",
    ManageSubscriptions: "Manage Subscriptions",
    MapFloatingToolbarVizCheckBox: "Show View Toolbar",
    MapForceMapsToOfflineLearnMoreMessage: "Your Tableau Server is configured to use the Offline style for the background map.",
    MapGeoSearchVizCheckBox: "Show Map Search",
    MapOptionsDialogTitle: "Map Options",
    MapOptionsDropDownLabel: "Units:",
    MapOptionsLayerControlCheckbox: "Show Layer Control",
    MapOptionsUnitAutomatic: "Automatic",
    MapOptionsUnitMetric: "Metric",
    MapOptionsUnitUS: "U.S.",
    MapScaleVizibilityCheckBox: "Show Map Scale",
    MapVizNavCheckBox: "Allow Pan And Zoom",
    MapsSearchViewClearInputTooltip: "Clear Search",
    MapsSearchViewInitialText: "Search Map",
    March: "March",
    MarchNarrow: "M",
    MarchShort: "Mar",
    MarkTextOneMark: "{0} mark",
    MarksCardDropdownAddZoom: "Add to Zoom Extent",
    MarksCardDropdownDisableSelection: "Disable Selection",
    MarksCardDropdownDuplicate: "Duplicate",
    MarksCardDropdownHide: "Hide",
    MarksCardDropdownMoveDown: "Move Down",
    MarksCardDropdownMoveUp: "Move Up",
    MarksCardDropdownRemove: "Remove",
    MarksCardDropdownRename: "Rename",
    MarksCardDropdownReplicatePanes: "Replicate Across Panes",
    MarksTextMultiMark: "{0} marks",
    MarksToLabelAllowOverlapLabel: "Allow labels to overlap other marks",
    MarksToLabelControlLabel: "Marks to Label",
    MarksToLabelFieldLabel: "Field",
    MarksToLabelLabelEndOfLine: "Label end of line",
    MarksToLabelLabelMaxValueLabel: "Label maximum value",
    MarksToLabelLabelMinValueLabel: "Label minimum value",
    MarksToLabelLabelStartOfLine: "Label start of line",
    MarksToLabelModeAll: "All",
    MarksToLabelModeHighlight: "Highlighted",
    MarksToLabelModeLineEnds: "Line Ends",
    MarksToLabelModeMostRecent: "Most Recent",
    MarksToLabelModeRange: "Min/Max",
    MarksToLabelModeSelection: "Selected",
    MarksToLabelOptionsLabel: "Options",
    MarksToLabelScopeCell: "Cell",
    MarksToLabelScopeDefault: "Pane",
    MarksToLabelScopeLabel: "Scope",
    MarksToLabelScopeMultiMark: "Line/Pie",
    MarksToLabelScopePane: "Pane",
    MarksToLabelScopeTable: "Table",
    May: "May",
    MayNarrow: "M",
    MayShort: "May",
    MenuBackButton: "Back",
    MessageCharacterLimit: "{0} of {1} characters",
    MetaDataGrid_ConnectionColor: "Connection Color",
    MetaDataGrid_DataType: "Data Type",
    MetaDataGrid_FieldName: "Field Name",
    MetaDataGrid_RemoteFieldName: "Remote Field Name",
    MetaDataGrid_Table: "Table",
    MetricsToolbarButtonLabel: "Metrics",
    Minutes: "{0} minutes",
    MissingValidEmailAddressAlert: "To subscribe, add an email address to your account.",
    Monday: "Monday",
    MondayNarrow: "M",
    MondayShort: "Mon",
    MoreActions: "More Actions",
    NewDashboardName: "New Dashboard",
    NewDataSource: "New Data Source",
    NewStoryName: "New Story",
    NewWorksheetName: "New Worksheet",
    NextExpextedSubscriptionBasedOnExtraxtRefresh: "This triggers a subscription when a data extract refresh completes.",
    NotificationIntervalDaily: "Daily at most",
    NotificationIntervalEveryTime: "As frequently as possible",
    NotificationIntervalHourly: "Hourly at most",
    NotificationIntervalOnlyOnce: "Once—the first time it’s true",
    NotificationIntervalWeekly: "Weekly at most",
    November: "November",
    NovemberNarrow: "N",
    NovemberShort: "Nov",
    NumberEnding: "{0}th",
    NumericBinsBinSizeLabel: "Size of bins:",
    NumericBinsCntDLabel: "Count Distinct:",
    NumericBinsDiffLabel: "Difference:",
    NumericBinsFieldNameLabel: "New field name: ",
    NumericBinsMaxLabel: "Maximum:",
    NumericBinsMinLabel: "Minimum:",
    NumericBinsRangeOfValuesLabel: "Range of Values:",
    OAuthFailureForUnsavedWorkbook: "You must save this workbook before the Einstein Discovery Analytics Extensions can be used. Please save the workbook and try again.",
    OAuthMissingPassword: "Missing Password",
    OAuthReauthenticateButton: "Sign In",
    OAuthReauthenticateMessage: "If you can’t connect, contact your Tableau administrator.",
    OAuthReauthenticateTitle: "You need to sign in again.",
    October: "October",
    OctoberNarrow: "O",
    OctoberShort: "Oct",
    OldGroupWarning: "The group was created in an old version of Tableau and cannot be used in calculations. ",
    OldGroupWarningLink: "Create a copy.",
    OpenInTableauMobile: "Open in Tableau Mobile",
    OpenOnDesktopDialogPrimaryActionLabel: "Close Workbook",
    OperatorAbove: "Above",
    OperatorAboveOrEqual: "Above or equal to",
    OperatorBelow: "Below",
    OperatorBelowOrEqual: "Below or equal to",
    OperatorEqual: "Equal to",
    PanZoomSelectToolsAppendTooltip: "Add to Selection",
    PanZoomSelectToolsCloseButtonTooltipMobile: "Exit Selection Mode",
    PanZoomSelectToolsLassoSelectionTooltip: "Lasso (D)",
    PanZoomSelectToolsLassoSelectionTooltipMobile: "Lasso Selection",
    PanZoomSelectToolsPanTooltip: "Pan (F)",
    PanZoomSelectToolsPanTooltipMobile: "Pan",
    PanZoomSelectToolsRadialSelectionTooltip: "Radial (S)",
    PanZoomSelectToolsRadialSelectionTooltipMobile: "Radial Selection",
    PanZoomSelectToolsRectangularSelectionTooltip: "Rectangle (A)",
    PanZoomSelectToolsRectangularSelectionTooltipMobile: "Rectangular Selection",
    PanZoomSelectToolsZoomAreaTooltip: "Zoom Area (Z)",
    PanZoomSelectToolsZoomHomeTooltip: "Zoom Home",
    PanZoomSelectToolsZoomInTooltip: "Zoom In (Double-Click)",
    PanZoomSelectToolsZoomOutTooltip: "Zoom Out (Shift+Double-Click)",
    PdfDialogClearAll: "Clear All",
    PdfDialogContentStory: "This Story",
    PdfDialogOrientation: "Orientation",
    PdfDialogPaperSize: "Paper Size",
    PdfDialogScalingLabel: "Scaling",
    PdfDialogSelectAll: "Select All",
    PdfDialogSelectionCounter: "{0} of {1}",
    PdfDialogSelectionCounterLabel: "Sheets Selected",
    PdfDialogSheetSelectionLabel: "Sheet Selection",
    PdfDialogSheetSelector: "Sheet Selector",
    PdfDialogSheetsFromDashboard: "Specific sheets from this dashboard",
    PdfDialogSheetsFromWorkbook: "Specific sheets from this workbook",
    PdfDialogThumbnailPageSizeLabel: "Page Size",
    PdfExportFitOneHigh: "At most 1 page high",
    PdfExportFitOneWide: "At most 1 page wide",
    PdfExportFitTwoHigh: "At most 2 pages high",
    PdfExportFitTwoWide: "At most 2 pages wide",
    PdfExportGeneratingPdf: "Generating PDF...",
    PdfExportMessageError: "Error producing PDF!",
    PdfExportMessageSettings: "Getting PDF settings from server.",
    PdfExportMessageSettingsError: "Error: Could not retrieve PDF settings from server.",
    PdfExportPageOrientationLandscape: "Landscape",
    PdfExportPageOrientationPortrait: "Portrait",
    PdfExportPageOrientationPrinter: "Printer",
    PdfExportPageScaleAuto: "Automatic",
    PdfExportPageScalePercent: "{0}%",
    PdfExportPageSizeA3: "A3",
    PdfExportPageSizeA4: "A4",
    PdfExportPageSizeA5: "A5",
    PdfExportPageSizeB4: "B4",
    PdfExportPageSizeB5: "B5",
    PdfExportPageSizeExecutive: "Executive",
    PdfExportPageSizeFolio: "Folio",
    PdfExportPageSizeLedger: "Ledger",
    PdfExportPageSizeLegal: "Legal",
    PdfExportPageSizeLetter: "Letter",
    PdfExportPageSizeNote: "Note",
    PdfExportPageSizeQuarto: "Quarto",
    PdfExportPageSizeStatement: "Statement",
    PdfExportPageSizeTabloid: "Tabloid",
    PdfExportPageSizeUnspecified: "Unspecified",
    PdfExportTitlePDF: "Download PDF",
    PressBackButtonMessage: "Use the back button to return to a valid view.",
    PrintPdfDialogContentRequired: "Select at least one sheet to download.",
    PrintPdfDialogMessage: "The PDF is ready to download.",
    PrintPdfDialogTitle: "Download PDF",
    PublicAuthSaveErrorTitle: "Couldn’t save workbook",
    QuantitativeColorCenter: "Center",
    QuantitativeColorDialogTitle: "Edit Colors {0}",
    QuantitativeColorEnableSteps: "Stepped color",
    QuantitativeColorEnd: "End",
    QuantitativeColorEndSwatch: "End color, custom color {0}",
    QuantitativeColorFullColorRange: "Use full color range",
    QuantitativeColorHideAdvanced: "Hide Advanced",
    QuantitativeColorIncludeTotals: "Include totals",
    QuantitativeColorPaletteLabel: "Palette",
    QuantitativeColorReset: "Reset",
    QuantitativeColorReverse: "Reverse",
    QuantitativeColorShowAdvanced: "Show Advanced",
    QuantitativeColorStart: "Start",
    QuantitativeColorStartSwatch: "Start color, custom color {0}",
    QuantitativeColorSteps: "steps",
    QuickFilterAll: "(All)",
    QuickFilterAllValues: "All Values",
    QuickFilterApply: "Apply",
    QuickFilterCancel: "Cancel",
    QuickFilterClearDisabled: "Showing All Values",
    QuickFilterClearEnabled: "Click to Show All Values",
    QuickFilterConditionalsCondition: "Condition",
    QuickFilterConditionalsLimit: "Limit",
    QuickFilterDomainCascading: "All Values in Hierarchy",
    QuickFilterDomainCascadingContext: "All Values in Hierarchy and Context",
    QuickFilterDomainContext: "All Values in Context",
    QuickFilterDomainDatabase: "All Values in Database",
    QuickFilterDomainRelevant: "Only Relevant Values",
    QuickFilterDomainShowFewerValues: "Show Fewer Values",
    QuickFilterDomainShowMoreValues: "Show More Values",
    QuickFilterExclusive: "Exclusive",
    QuickFilterInclusive: "Inclusive",
    QuickFilterMultiSelect: "Multiple",
    QuickFilterMultipleValues: "(Multiple values)",
    QuickFilterNoItems: "No Items.",
    QuickFilterNonNullValues: "Non-Null Values",
    QuickFilterNone: "(None)",
    QuickFilterOnlyNullValues: "Only Null Values",
    QuickFilterSearch: "Search",
    QuickFilterSearchAddItemCtrlEnter: "Add Item (Ctrl+Enter)",
    QuickFilterSearchAddItemEnter: "Add Item (Enter)",
    QuickFilterSearchCancel: "Cancel Search",
    QuickFilterSearchClearTooltip: "Clear (Esc)",
    QuickFilterSearchCloseTooltip: "Close (Esc)",
    QuickFilterSearchDataIsCaseSensitive: "Data is case sensitive.",
    QuickFilterSearchFoundMatches: "Found {0} matches",
    QuickFilterSearchHint: "Enter Text to Search",
    QuickFilterSearchInvalidDataMemberSingular: "\"{0}\" is not a valid member of the filter.",
    QuickFilterSearchInvalidDataMembersDialogTitle: "Invalid Data Members",
    QuickFilterSearchInvalidDataMembersPlural: "The following values are not valid members of the filter:",
    QuickFilterSearchNoMatches: "No matches.",
    QuickFilterSearchTooltip: "Search (Enter)",
    QuickFilterShowContextMenu: "Show Quick Filter Context Menu",
    QuickFilterShowLargerRange: "Show Larger Range",
    QuickFilterShowSmallerRange: "Show Smaller Range",
    QuickFilterSingleSelect: "Single",
    QuickFilterTitleBarExclusive: "{0} (Exclusive)",
    QuickFilterUnknown: "<unknown>",
    QuickFilterValuesInRange: "Values in Range",
    QuickFilterValuesInRangeOrNull: "Values in Range or Null",
    RedirectToApp: "Redirect to App Store?",
    RefLineEditorInputTitle: "Value:",
    RefreshDataSourceListLabel: "Refresh list",
    RelDateAnchored_curr_day: "Anchor day",
    RelDateAnchored_curr_hour: "Anchor hour",
    RelDateAnchored_curr_minute: "Anchor minute",
    RelDateAnchored_curr_month: "Anchor month",
    RelDateAnchored_curr_quarter: "Anchor quarter",
    RelDateAnchored_curr_second: "Anchor second",
    RelDateAnchored_curr_week: "Anchor week",
    RelDateAnchored_curr_year: "Anchor year",
    RelDateAnchored_last_day: "Yesterday",
    RelDateAnchored_last_hour: "Previous hour",
    RelDateAnchored_last_minute: "Previous minute",
    RelDateAnchored_last_month: "Previous month",
    RelDateAnchored_last_quarter: "Previous quarter",
    RelDateAnchored_last_second: "Previous second",
    RelDateAnchored_last_week: "Previous week",
    RelDateAnchored_last_year: "Previous year",
    RelDateAnchored_lastn_day: "Last % days",
    RelDateAnchored_lastn_hour: "Last % hours",
    RelDateAnchored_lastn_minute: "Last % minutes",
    RelDateAnchored_lastn_month: "Last % months",
    RelDateAnchored_lastn_quarter: "Last % quarters",
    RelDateAnchored_lastn_second: "Last % seconds",
    RelDateAnchored_lastn_week: "Last % weeks",
    RelDateAnchored_lastn_year: "Last % years",
    RelDateAnchored_next_day: "Tomorrow",
    RelDateAnchored_next_hour: "Next hour",
    RelDateAnchored_next_minute: "Next minute",
    RelDateAnchored_next_month: "Next month",
    RelDateAnchored_next_quarter: "Next quarter",
    RelDateAnchored_next_second: "Next second",
    RelDateAnchored_next_week: "Next week",
    RelDateAnchored_next_year: "Next year",
    RelDateAnchored_nextn_day: "Next % days",
    RelDateAnchored_nextn_hour: "Next % hours",
    RelDateAnchored_nextn_minute: "Next % minutes",
    RelDateAnchored_nextn_month: "Next % months",
    RelDateAnchored_nextn_quarter: "Next % quarters",
    RelDateAnchored_nextn_second: "Next % seconds",
    RelDateAnchored_nextn_week: "Next % weeks",
    RelDateAnchored_nextn_year: "Next % years",
    RelDateAnchored_todate_day: "Day to anchor",
    RelDateAnchored_todate_hour: "Hour to anchor",
    RelDateAnchored_todate_minute: "Minute to anchor",
    RelDateAnchored_todate_month: "Month to anchor",
    RelDateAnchored_todate_quarter: "Quarter to anchor",
    RelDateAnchored_todate_second: "Second to anchor",
    RelDateAnchored_todate_week: "Week to anchor",
    RelDateAnchored_todate_year: "Year to anchor",
    RelDateFilterDays: "Days",
    RelDateFilterHours: "Hours",
    RelDateFilterMinutes: "Minutes",
    RelDateFilterMonths: "Months",
    RelDateFilterPreview: "{0} to {1}",
    RelDateFilterQuarters: "Quarters",
    RelDateFilterWeeks: "Weeks",
    RelDateFilterYears: "Years",
    RelDatePickerFiveYears: "5 years",
    RelDatePickerFiveYearsAbbrev: "5y",
    RelDatePickerOneDay: "1 day",
    RelDatePickerOneDayAbbrev: "1d",
    RelDatePickerOneMonth: "1 month",
    RelDatePickerOneMonthAbbrev: "1m",
    RelDatePickerOneWeek: "1 week",
    RelDatePickerOneWeekAbbrev: "1w",
    RelDatePickerOneYear: "1 year",
    RelDatePickerOneYearAbbrev: "1y",
    RelDatePickerThreeMonths: "3 months",
    RelDatePickerThreeMonthsAbbrev: "3m",
    RelDate_curr_day: "Today",
    RelDate_curr_hour: "This hour",
    RelDate_curr_minute: "This minute",
    RelDate_curr_month: "This month",
    RelDate_curr_quarter: "This quarter",
    RelDate_curr_second: "This second",
    RelDate_curr_week: "This week",
    RelDate_curr_year: "This year",
    RelDate_last_day: "Yesterday",
    RelDate_last_hour: "Previous hour",
    RelDate_last_minute: "Previous minute",
    RelDate_last_month: "Previous month",
    RelDate_last_quarter: "Previous quarter",
    RelDate_last_second: "Previous second",
    RelDate_last_week: "Previous week",
    RelDate_last_year: "Previous year",
    RelDate_lastn_day: "Last % days",
    RelDate_lastn_hour: "Last % hours",
    RelDate_lastn_minute: "Last % minutes",
    RelDate_lastn_month: "Last % months",
    RelDate_lastn_quarter: "Last % quarters",
    RelDate_lastn_second: "Last % seconds",
    RelDate_lastn_week: "Last % weeks",
    RelDate_lastn_year: "Last % years",
    RelDate_next_day: "Tomorrow",
    RelDate_next_hour: "Next hour",
    RelDate_next_minute: "Next minute",
    RelDate_next_month: "Next month",
    RelDate_next_quarter: "Next quarter",
    RelDate_next_second: "Next second",
    RelDate_next_week: "Next week",
    RelDate_next_year: "Next year",
    RelDate_nextn_day: "Next % days",
    RelDate_nextn_hour: "Next % hours",
    RelDate_nextn_minute: "Next % minutes",
    RelDate_nextn_month: "Next % months",
    RelDate_nextn_quarter: "Next % quarters",
    RelDate_nextn_second: "Next % seconds",
    RelDate_nextn_week: "Next % weeks",
    RelDate_nextn_year: "Next % years",
    RelDate_todate_day: "Day to date",
    RelDate_todate_hour: "Hour to date",
    RelDate_todate_minute: "Minute to date",
    RelDate_todate_month: "Month to date",
    RelDate_todate_quarter: "Quarter to date",
    RelDate_todate_second: "Second to date",
    RelDate_todate_week: "Week to date",
    RelDate_todate_year: "Year to date",
    RequestAbortedByBrowser: "Request Aborted by Browser",
    RequestCountExceededTitle: "Request Count Exceeded",
    RequestCountExceededWarning: "Request count has exceeded the number allowed in the alloted time.",
    ResourceLimited: "resource is limited",
    RowByColumn: "{0} row by {1} column",
    RowByColumns: "{0} row by {1} columns",
    RowCountLabel: "rows",
    RowsByColumn: "{0} rows by {1} column",
    RowsByColumns: "{0} rows by {1} columns",
    Saturday: "Saturday",
    SaturdayNarrow: "S",
    SaturdayShort: "Sat",
    SaveAsFailedMessage: "You don\'t have permission to save this workbook. For assistance, contact your administrator.",
    SaveIncompleteWorkbookWarning: "Not all views were shared when this workbook was published. Saving the workbook will overwrite the original workbook, and the unshared views will be lost. Consider using Save As instead.",
    SaveNoPublishedSheetsBody: "A workbook must have at least one published sheet to be saved.  Right-click on a tab to publish a sheet.",
    SaveNoPublishedSheetsTitle: "Cannot Save",
    ScheduleDailyDescription: "Daily at {0}",
    ScheduleEvery30MinutesDescription: "Every 30 minutes at 15 and 45 minutes after the hour",
    ScheduleEveryOneHourAtXMinutesPastDescription: "Every hour at {0} minutes after the hour",
    ScheduleEveryOneHourDescription: "Every hour",
    ScheduleEveryXHoursStartingAtYDescription: "Every {0} hours starting at {1}",
    ScheduleEveryXMinutesDescription: "Every {0} minutes",
    ScheduleHourlyDescription: "Every {0} from {1} to {2}",
    ScheduleMonthlyDescription: "On the {0} day of the month at {1}",
    ScheduleMonthlyDescriptionLast: "On the last day of the month at {0}",
    ScheduleMonthlyDescriptionSecondToLast: "On the second to last day of the month at {0}",
    ScheduleWeeklyDescription: "Weekly at {0} on {1}",
    SchemaSearchFilterCalculation: "Calculation",
    SchemaSearchFilterComment: "Comment",
    SchemaSearchFilterDimension: "Dimension",
    SchemaSearchFilterMeasure: "Measure",
    SchemaSearchFilterTitle: "Filter by",
    ScratchpadTitle: "Scratchpad",
    SearchDataSources: "Search data sources",
    SearchResultsNotShownPlural: "{0} results not shown",
    SearchResultsNotShownSingular: "1 result not shown",
    SearchResultsNotShownZero: "0 results not shown",
    SecondEnding: "{0}nd",
    SecurityBlockedURLActionHeader: "URL Blocked",
    SecurityBlockedURLActionMessage: "A potentially unsafe URL has been blocked.",
    SecurityWarningURLActionHeader: "Security Warning",
    SecurityWarningURLActionMessage: "This hyperlink may run potentially harmful software on your computer. Are you sure you want to follow this hyperlink?",
    SelectDataSource: "Select data source",
    SelectDataSourcePublishedDSDoesNotExist: "The selected data source does not exist on the server.",
    SelectDataSourcePublishedDSSubError: "Select a different data source",
    SelectLinkLabel: "Select",
    SelectText: "Select",
    SelectedMarksText: "{0} of {1} marks",
    September: "September",
    SeptemberNarrow: "S",
    SeptemberShort: "Sep",
    SerialScheduleDescription: "{0} - {1}",
    SerialScheduleDescriptionSuffix: "Sequential (slower)",
    ServerAdmin: "server administrator",
    ServerDataSourceConnectedWorkbooks: "Workbooks",
    ServerDataSourceConnectedWorkbooksTooltip: "Number of workbooks connected to a data source",
    ServerDataSourceConnectionType: "Connection Type",
    ServerDataSourceConnectsTo: "Connects To",
    ServerDataSourceConnectsToSeveral: "{0} + {1}",
    ServerDataSourceExtract: "Extract",
    ServerDataSourceLive: "Live",
    ServerDataSourceLiveOrLastExtract: "Live / Last extract",
    ServerDataSourceName: "Name",
    ServerDataSourceOwner: "Owner",
    ServerDataSourceProject: "Project",
    ServerDataSourceTotalViews: "Views: All",
    ServerErrorGeneral: "An error occurred communicating with the server ({0}).<br>This may be a temporary network condition.  Please retry the operation.<br>If this condition persists, contact your system administrator.",
    ServerErrorInvalidJSON: "An error occurred communicating with the server (Invalid JSON).",
    ServerErrorRejected: "Request Rejected by Server",
    ServerErrorRejectedMessage: "The server could not respond due to a malformed request.<br>This may be a temporary network condition.  Please retry the operation.<br>If this condition persists, contact your system administrator.",
    ServerErrorTitle: "Server Error",
    ServerErrorUnexpected: "Unexpected Server Error",
    ServerErrorUnknown: "Tableau experienced an unexpected server error. Try again, or contact your Tableau Server Administrator.",
    SessionEndedAlertMessage: "Would you like to reset the view?",
    SessionEndedAlertTitle: "Session Ended by Server",
    SessionForbiddenActionMsg: "You are not authorized to perform this action.",
    SessionForbiddenActionTitle: "Forbidden Action",
    SessionInactivityWarning: "Welcome back. We\'re reloading your content...",
    SessionRecoveryWarning: "We may have lost your last few changes. Make sure they still remain.",
    SessionUnknownErrorTitle: "Unknown Server Error",
    SetControlIncludeAllDisabled: "All Set Values Included",
    SetControlIncludeAllEnabled: "Click to Include All Set Values",
    ShareDialogAndroidLinkText: "Tap icon to open link",
    ShareDialogDisplayOptions: "Display Options",
    ShareDialogDoneButton: "Done",
    ShareDialogEmail: "Email:",
    ShareDialogEmailHelp: "Copy and Paste link into your email message",
    ShareDialogEmailLink: "Email",
    ShareDialogEmbed: "Embed:",
    ShareDialogEmbedCodeTableauText: "Learn About Tableau",
    ShareDialogEmbedHelp: "Copy and Paste HTML code to embed the view in your website",
    ShareDialogEnterUriForBlogEntry: "Enter the URI for the blog entry",
    ShareDialogEnterValueBetween: "Enter a value between {0} and {1}",
    ShareDialogFacebookLink: "Facebook",
    ShareDialogHeight: "Height:",
    ShareDialogInvalidHeight: "Invalid height.",
    ShareDialogInvalidWidth: "Invalid width.",
    ShareDialogLink: "Link:",
    ShareDialogMobileEmailText: "Tap icon to send the link by email",
    ShareDialogMobileLinkText: "Tap and hold icon to access other sharing options",
    ShareDialogPleaseEnterIntegerBetween: "Please enter an integer between {0} and {1}",
    ShareDialogShowTabs: "Show Tabs",
    ShareDialogShowToolbar: "Show Toolbar",
    ShareDialogTitle: "Share View",
    ShareDialogTitleForView: "Share View",
    ShareDialogToastError: "Error: ",
    ShareDialogToastSuccess: "Success: ",
    ShareDialogTwitterLink: "Tweet",
    ShareDialogUrlForRssLinks: "URL for RSS links:",
    ShareDialogWaitingEmbedMessage: "creating your custom embed code ...",
    ShareDialogWaitingLinkMessage: "creating your custom link ...",
    ShareDialogWidth: "Width:",
    ShareViewOptions: "Share View Options",
    SheetReconnectEditConnectionLabel: "Edit Connection",
    SheetReconnectEditingNotSupported: "This data connection doesn\'t currently support editing.",
    SheetReconnectErrorMessage: "{0}.",
    SheetReconnectLocateFileLabel: "Locate File",
    SheetReconnectSignInLabel: "Sign In",
    SheetReconnectSubtitle: "There was a problem connecting to the \"{0}\" data source.",
    SheetReconnectTitle: "Worksheet Unavailable",
    ShowAliases: "Show aliases",
    ShowDetailsLabel: "Show details",
    ShowHiddenFields: "Show hidden fields",
    SignOutFailedMessage: "Failed to sign out. Please try again.",
    SiteAdmin: "site administrator",
    SizeLegendTextMarkSwatch: "Abc",
    SnapshotApplicationErrorMessage: "Couldn\'t apply snapshot from {0} to this view",
    SortAtoZAscending: "A to Z ascending",
    SortAtoZAscendingPerTable: "A to Z ascending per table",
    SortDataSourceOrder: "Data source order",
    SortFields: "Sort fields",
    SortModified: "Modified",
    SortZtoADescending: "Z to A descending",
    SortZtoADescendingPerTable: "Z to A descending per table",
    SpecialAll: "All",
    SpecialError: "#Error",
    SpecialManyValues: "*",
    SpecialMissing: "#Missing",
    SpecialNoAccess: "#NoAccess",
    SpecialRagged: "#Ragged",
    SpecialSkipped: "#Skipped",
    SpecialValuesHeading: "Special Values (e.g. NULL)",
    SpecialValuesMarkLabel: "Marks",
    SpecialValuesMarksHideBreakLines: "Hide (break lines)",
    SpecialValuesMarksHideConnectLines: "Hide (connect lines)",
    SpecialValuesMarksShowAtDefaultValue: "Show at Default Value",
    SpecialValuesMarksShowAtIndicator: "Show at Indicator",
    SpecialValuesTextLabel: "Text",
    SpecialValuesTextPlaceholder: "(Blank)",
    SpecialWildcard: "Wildcard",
    StopUsingAsLinkingField: "Stop using {0} as linking field",
    StoryContentPaneBlankButton: "Blank",
    StoryContentPaneDuplicateButton: "Duplicate",
    StoryContentPaneSaveAsNewPointButton: "Save as New",
    StoryContentPaneTitle: "Story",
    StoryContentShowCaptions: "Show captions",
    StoryContentShowTitles: "Show title",
    StoryEmptyCaptionText: "Add a caption",
    StoryEmptyDashboardStoryPointSubtitle: "Add worksheets to the dashboard.",
    StoryEmptyDashboardStoryPointTitle: "This dashboard is empty.",
    StoryEmptyFlipboardSubtitle: "To add a sheet here",
    StoryEmptyFlipboardSubtitleBE: "Drag or double-click from the list at left.",
    StoryEmptyFlipboardTitle: "Double-click from the list on the left",
    StoryEmptyFlipboardTitleBE: "Add sheets here",
    StoryEmptyWorksheetStoryPointSubtitle: "Create a viz in the worksheet.",
    StoryEmptyWorksheetStoryPointTitle: "This worksheet is empty.",
    StoryNavigatorStyle: "Navigator Style",
    StoryNavigatorTypeArrowOnly: "Arrows only",
    StoryNavigatorTypeCaption: "Caption boxes",
    StoryNavigatorTypeDot: "Dots",
    StoryNavigatorTypeNumber: "Numbers",
    StoryNavigatorUpdated: "Updated",
    StoryNewPointSectionTitle: "New story point",
    StoryPointDeleteTooltip: "Delete",
    StoryPointNavigatorLocationBottom: "Bottom",
    StoryPointNavigatorLocationTitle: "Navigator Location",
    StoryPointNavigatorLocationTop: "Top",
    StoryPointNavigatorShowArrows: "Show arrows",
    StoryPointRevertTooltip: "Revert",
    StoryPointSaveAsNewTooltip: "Save as new point",
    StoryPointUpdateButton: "Update",
    StoryReplaceMessage: "Replace",
    SubscribeButtonTooltip: "Subscribe",
    SubscribeCancel: "Cancel",
    SubscribeContent: "Content:",
    SubscribeDone: "Done",
    SubscribeEnterAddress: "To receive subscriptions enter your email address.",
    SubscribeFailure: "Subscription failed.",
    SubscribeInvalidAddress: "Please enter a valid email address. ",
    SubscribeNext: "Next",
    SubscribeOthers: "Subscribe Others",
    SubscribeOthersFailed: "Could not complete subscription for {0} subscribers.",
    SubscribeOthersSearchPlaceholder: "Subscriber name or username",
    SubscribeOthersSuccess: "Created {0} subscriptions.",
    SubscribeSelf: "Subscribe me",
    SubscribeSelfLabel: "I want to subscribe",
    SubscribeSheet: "This Sheet",
    SubscribeSingleSuccess: "Created 1 subscription.",
    SubscribeSubject: "Subject:",
    SubscribeSubscribe: "Subscribe",
    SubscribeSuccess: "Subscription successfully saved.",
    SubscribeTitle: "Subscribe",
    SubscribeTo: "To:",
    SubscribeViewsToggleLabel: "Subscribe to",
    SubscribeWorkbook: "Sheets in Workbook",
    SuggestBinSizeButtonText: "Suggest",
    SumOf: "SUM of",
    SummaryViewDataCaption: "Summary",
    Sunday: "Sunday",
    SundayNarrow: "S",
    SundayShort: "Sun",
    SupressedExceptionTitle: "Temporary issues displaying this dashboard",
    SwapSheets: "Swap Sheets",
    TabAuthCategoricalColorEditorAssignPalette: "Assign Palette",
    TabAuthCategoricalColorEditorReset: "Reset",
    TabAuthCategoricalColorEditorSelectItem: "Select Data Item",
    TabAuthCategoricalColorEditorSelectPalette: "Select Color Palette",
    TabAuthColorEditButton: "Edit Colors...",
    TabAuthColorEditLabel: "Color",
    TabAuthColorEditLegendButtonTooltip: "Edit Colors...",
    TabAuthColorEditorDialogTitle: "Edit Colors [{0}]",
    TabAuthEditLabelButton: "Edit Label...",
    TabAuthEditTextButton: "Edit Text...",
    TabAuthMarksColorBorderLabel: "Border",
    TabAuthMarksColorHaloLabel: "Halo",
    TabAuthSaveDatasourceConfirmMsg: "Save the data source \"{0}\" for shared use on the server?",
    TabAuthSaveDatasourceDialogTitle: "Save Data Source",
    TabAuthSaveDatasourceErrorDialogTitle: "Save Data Source Error",
    TabAuthSaveDatasourceNotReplacedSuccessMessage: "The data source \"{0}\" was saved, but a problem occurred while replacing this workbook\'s connection.",
    TabAuthSaveDatasourceNotReplacedSuccessTitle: "Save Data Source Success",
    TabAuthSaveDatasourceOverwriteCheckboxLabel: "Replace existing published data source",
    TabAuthSaveDatasourceReplaceCheckboxLabel: "Update workbook to connect to the saved data source",
    TabAuthSaveDatasourceReplacedSuccessMessage: "Your data source has been saved.",
    TabAuthSaveDatasourceReplacedSuccessTitle: "Save Data Source Success",
    TabAuthSaveDatasourceSuccessDialogTitle: "Save Data Source Success",
    TabAuthSaveDatasourceSuccessMessage: "Your data source has been saved. The project settings determine \"Connect to\" and other permissions for this data source. Browse to the Data Sources page to see this data source and its properties.",
    TableCalcAddSecondary: "Add secondary calculation",
    TableCalcAtTheLevel: "At the level",
    TableCalcComputeCompoundedRate: "Compute compounded rate",
    TableCalcComputeTotalAcrossPages: "Compute total across all pages",
    TableCalcComputeUsing: "Compute Using",
    TableCalcDialogTitle: "Table Calculation",
    TableCalcInvalidRestartEveryField: "<invalid>",
    TableCalcMissingSortField: "<missing>",
    TableCalcNestedCalculations: "Nested Calculations",
    TableCalcPrimaryTitle: "Primary Calculation Type",
    TableCalcRelativeTo: "Relative to",
    TableCalcRestartingEvery: "Restarting every",
    TableCalcSecondaryTitle: "Secondary Calculation Type",
    TableCalcShowCalculationAssistance: "Show calculation assistance",
    TableCalcSingleTitle: "Calculation Type",
    TableCalcSortAscending: "Ascending",
    TableCalcSortAutomatic: "Specific dimensions",
    TableCalcSortCustom: "Custom",
    TableCalcSortDescending: "Descending",
    TableCalcSortOrder: "Sort order",
    TableCalcSpecificDimensions: "Specific Dimensions",
    TableCalcVisualStructure: "Visual Structure",
    TableCalcWindowCurrentValue: "Current Value",
    TableCalcWindowNullSetting: "Null if there are not enough values",
    TableauMobileWebBannerLabel: "Tableau",
    TableauPublic: "Tableau Public",
    ThirdEnding: "{0}rd",
    Thursday: "Thursday",
    ThursdayNarrow: "T",
    ThursdayShort: "Thu",
    TimeLimitExceededTitle: "Session Time Limit Exceeded",
    TimeLimitExceededWarning: "Computing the current visualization has exceeded the session time limit.",
    ToolbarAboutTableau: "About Tableau",
    ToolbarBrowserNotSupportedDownloadExplanation: "Download isn\'t supported by this browser. Use a different browser and try again.",
    ToolbarConnectToDataSource: "Add New Data Source",
    ToolbarCurrentView: "Current View",
    ToolbarCustomViewsDefault: "{0} (default)",
    ToolbarCustomViewsDeleteButtonTooltip: "Delete this view",
    ToolbarCustomViewsEmptyPlaceholder: "Nothing saved yet",
    ToolbarCustomViewsEnterManageButtonText: "Manage",
    ToolbarCustomViewsErrorChangingPublicPrivateState: "Error updating the public/private state on the custom view.",
    ToolbarCustomViewsErrorDeleting: "Error deleting the custom view.",
    ToolbarCustomViewsErrorInvalidName: "Please enter a valid custom view name.",
    ToolbarCustomViewsErrorRenaming: "Error renaming the custom view.",
    ToolbarCustomViewsErrorSavingView: "Error saving custom view.",
    ToolbarCustomViewsErrorSettingDefault: "Error setting the default custom view.",
    ToolbarCustomViewsExitManageButtonText: "Done",
    ToolbarCustomViewsHideViewButtonTooltipWhenPrivate: "This view is private",
    ToolbarCustomViewsHideViewButtonTooltipWhenPublic: "This view is public",
    ToolbarCustomViewsMakeItMyDefault: "Make it my default",
    ToolbarCustomViewsMyViews: "My Views",
    ToolbarCustomViewsOriginalView: "Original",
    ToolbarCustomViewsOtherViews: "Other Views",
    ToolbarCustomViewsRenameButtonTooltip: "Rename this view",
    ToolbarCustomViewsRenameUIClearButtonTooltip: "Cancel",
    ToolbarCustomViewsRenameUIPlaceholderText: "Rename this view",
    ToolbarCustomViewsSave: "Save",
    ToolbarCustomViewsSaveAreaFillerTextManage: "Manage",
    ToolbarCustomViewsSaveAreaFillerTextSelect: "Select Custom View",
    ToolbarCustomViewsSaveButtonDisabledTitle: "Please enter a name for the Custom View in the text field.",
    ToolbarCustomViewsSetDefaultButtonTooltip: "Set this view as your default",
    ToolbarCustomViewsSetDefaultButtonTooltipWhenCurrent: "This is your current default",
    ToolbarCustomViewsShareItWithOthers: "Make it public",
    ToolbarCustomViewsSharedView: "Shared",
    ToolbarCustomViewsTemplate: "View: {0}",
    ToolbarCustomViewsViewNamePlaceholder: "Name this view",
    ToolbarDisabledCrosstabDownloadExplanation: "The crosstab is not available for download.",
    ToolbarDisabledDataDownloadExplanation: "The data is not available for download.",
    ToolbarDisabledDownloadExplanation: "Click the view to enable data and crosstab download",
    ToolbarDisabledPdfImageDownloadExplanation: "Permissions are required to download an Image or PDF.",
    ToolbarDisabledPdfPptImageDownloadExplanation: "Download Image/PDF permission required.",
    ToolbarDisabledWorkbookDownloadExplanation: "Permissions are required to download the workbook.",
    ToolbarDownload: "Download",
    ToolbarDownloadSelectFormat: "Select your file format.",
    ToolbarEdit: "Edit",
    ToolbarEmbedTitle: "Embed Code",
    ToolbarEnterFullscreen: "Full Screen",
    ToolbarExitFullscreen: "Exit Full Screen",
    ToolbarExport: "Download",
    ToolbarExportCrosstab: "Crosstab",
    ToolbarExportData: "Data",
    ToolbarExportImage: "Image",
    ToolbarExportPowerPoint: "PowerPoint",
    ToolbarGoToTableauPublic: "Go to Tableau Public",
    ToolbarLearnMoreAboutTableau: "Learn more about Tableau",
    ToolbarLearnMoreAboutTableauPublic: "Learn more about Tableau Public",
    ToolbarMoreByAuthor: "more by this author",
    ToolbarMoreInfo: "More Information",
    ToolbarOriginalView: "Original View",
    ToolbarPauseAutomaticUpdates: "Pause Automatic Updates",
    ToolbarPrintToPdf: "PDF",
    ToolbarPublicAvailablePlatforms: "Available for {0} and {1}",
    ToolbarPublicDownloadLabelMobile: "Learn More",
    ToolbarPublicDownloadLabelWeb: "Get the App",
    ToolbarPublicExplanationText: "Create interactive graphs, maps, dashboards and apps. Publish them anywhere on the web. Anyone can do it. And it’s free.",
    ToolbarPublicExplanationTitle: "What\'s Tableau Public?",
    ToolbarRefreshData: "Refresh data for this view",
    ToolbarResumeAutomaticUpdates: "Resume Automatic Updates",
    ToolbarRevertAll: "Revert All",
    ToolbarSendTitle: "Link",
    ToolbarSetCurrentPage: "Set the current page",
    ToolbarShare: "Share",
    ToolbarShowPerformanceRecording: "Performance",
    ToolbarSubscribeAddGroupsHeader: "Add Users in Groups",
    ToolbarSubscribeAddGroupsLabel: "Subscribe Users in Groups",
    ToolbarSubscribeAddGroupsPlaceholder: "Add users in groups",
    ToolbarSubscribeAddUsersHeader: "Add Users",
    ToolbarSubscribeAddUsersLabel: "Subscribe Users",
    ToolbarSubscribeAddUsersOrGroupsPlaceholder: "Type to add users or groups",
    ToolbarSubscribeAddUsersOrGroupsSelected: "Selected",
    ToolbarSubscribeAddUsersPlaceholder: "Add users",
    ToolbarSubscribeAllView: "Entire Workbook",
    ToolbarSubscribeDataPresentCheckbox: "Don’t send if view is empty",
    ToolbarSubscribeEmailPlaceholder: "Email",
    ToolbarSubscribeFormat: "Format",
    ToolbarSubscribeFrequency: "Frequency",
    ToolbarSubscribeInclude: "Include",
    ToolbarSubscribeMessageEditorPlaceholder: "Add a custom message",
    ToolbarSubscribeMessageLabel: "Message (Optional)",
    ToolbarSubscribeMessageLabelOld: "Message",
    ToolbarSubscribeMessagePlaceholder: "Add a custom message",
    ToolbarSubscribeMessagePlaceholderOld: "Add a custom message (optional)",
    ToolbarSubscribeMissingSubject: "Missing subject",
    ToolbarSubscribeOnExtractRefresh: "When Data Refreshes",
    ToolbarSubscribeOnSchedule: "On Selected Schedule",
    ToolbarSubscribeSchedule: "Schedule",
    ToolbarSubscribeSubjectPlaceholder: "Subject",
    ToolbarSubscribeSubmitButton: "Subscribe",
    ToolbarSubscribeSubmitDisabledTitle: "Please make sure you have a valid schedule, email address, and subject to subscribe.",
    ToolbarSubscribeThisView: "This View",
    ToolbarSubscribeToImage: "Image",
    ToolbarSubscribeToImageAndPdf: "Image and PDF",
    ToolbarSubscribeToPdf: "PDF",
    ToolbarSubscribeUserMissingEmail: "Error: No email address associated with user {0}",
    ToolbarToggleAutoUpdate: "Toggle Auto Update",
    ToolbarViewCount: "{0} views",
    ToolbarWorkbook: "Tableau Workbook",
    TooltipPanZoomMessage: "Double-click to zoom / Press-and-hold to pan",
    TrendLineDialogFactorsSectionLabel: "Include the following fields as factors:",
    TrendLineDialogModelTypeSectionLabel: "Model type",
    TrendLineDialogOptionsSectionLabel: "Options",
    Tuesday: "Tuesday",
    TuesdayNarrow: "T",
    TuesdayShort: "Tue",
    UbertipClearSelection: "Clear<br/>Selection",
    UbertipCommand1Mobile: "Clear<br/>Selection",
    UbertipCommand7Mobile: "View Data",
    UbertipItemsSelected: "items selected",
    UbertipTooltip_Action_DownMobile: "Drill Down",
    UbertipTooltip_Action_UpMobile: "Drill Up",
    UbertipTooltip_ExcludeMobile: "Exclude",
    UbertipTooltip_GroupMobile: "Group Members",
    UbertipTooltip_KeepOnlyMobile: "Keep Only",
    UbertipTooltip_SortAscendingMobile: "Sort Ascending",
    UbertipTooltip_SortDescendingMobile: "Sort Descending",
    UbertipTooltip_SplitMobile: "Ungroup Members",
    UbertipTooltip_ViewDataMobile: "View Data",
    UnhandledExceptionMessage: "An unexpected error occurred. If you continue to receive this error please contact your Tableau Server Administrator.<br>Session ID: {0}<br>{1}",
    UnhandledExceptionTitle: "Unexpected Error",
    UnusedFilesInSaveWorkbookPublishedMessage: "There are unused files in the workbook. To publish these files, add them to the data source.",
    UnusedFilesInSaveWorkbookSavedMessage: "You have text files that aren’t included in the data source. If you want to save them, add them to the data source.",
    UploadBytes: "bytes",
    UploadGB: "GB",
    UploadKB: "KB",
    UploadMB: "MB",
    UseAsLinkingField: "Use {0} as linking field",
    UserHasNoEmailAddressWarning: "User has no email address in Tableau",
    ViewCommentsMobileWebBannerLabel: "To view comments,",
    ViewDataDownloadDataAsFile: "Download all rows as a text file",
    ViewDataH1: "View Data",
    ViewDataShowAllColumns: "Show all columns",
    ViewDataShowingRows: "Showing first {0} rows.",
    ViewDataSummary: "Summary",
    ViewDataUnderlying: "Full data",
    VizObjectTypeReferenceLine: "Reference Line",
    WaitDialogDefaultTitleStatus: "Processing...",
    WarningTitle: "Warning",
    WebZoneDisabled: "Web Page Objects are disabled for this site. For more information, contact your Tableau administrator.",
    WebZoneEmptyURL: "Choose a website URL using the object menu.",
    WebZoneHttpsEmbedHttpAuthoring: "Because the server is running HTTPS, the URL for this web page object must be specified using https:// instead of http://",
    WebZoneHttpsEmbedHttpView: "Unable to display web page object (URL must start with https://)",
    WebZoneUrlDialogTitle: "Edit URL",
    Wednesday: "Wednesday",
    WednesdayNarrow: "W",
    WednesdayShort: "Wed",
    WindowTableCalcNextValuesLabel: "Next values",
    WindowTableCalcPreviousValuesLabel: "Previous values",
    WindowTableCalcSummarizeUsing: "Summarize values using",
    WorkbookAccessWarningBody: "This could stop existing extract refreshes, alerts, and subscriptions for this workbook",
    WorkbookAccessWarningHeader: "Warning",
    WorkbookTemplatesCategoryLabel: "Dashboard Starters",
    WorkbookTemplatesExtractErrorBannerActionMessage: "Continue with sample data",
    WorkbookTemplatesExtractErrorBannerMessage: "Couldn\'t load your data in the dashboard. Check your email for details.",
    WorkbookTemplatesPublishErrorBannerActionMessage: "Try again",
    WorkbookTemplatesPublishErrorBannerMessage: "Couldn\'t publish workbook. Try again, or contact your administrator if issue persists.",
    WorkbookTemplatesSampleData: "Building data extract...",
    WorkbookTemplatesServiceDownMessage: "Dashboard Starters are not available at the moment. Please try again later.",
    WorkbookTemplatesSuccessBannerActionMessage: "Reload workbook",
    WorkbookTemplatesSuccessBannerMessage: "Your extract is finished. Reload the workbook to start exploring.",
    WorkbookTemplatesTypeLabel: "Starters",
    ZoneListTitle: "Layout - {0}"
  };

  function replaceAll(s, oldValue, newValue) {
    newValue = (newValue === undefined || newValue === null) ? '' : newValue;
    return s.split(oldValue).join(newValue);
  }

  w.tab = w.tab || {};
  if (!tab.Strings) {
    tab.Strings = {
      noLoc: function(str) { return str; },
      getString: function(strKey) { return typeof (tab.Strings[strKey]) === 'undefined' ? '!' + strKey + '!': tab.Strings[strKey]; }
    };
    for (var key in s) {
      if (s.hasOwnProperty(key)) {
        tab.Strings[key] = function() {
          var k = key, hasParams = /{[^}{]+}/.test(s[k]);
          return hasParams ?
            function() {
              var formattedString = s[k];
              for (var i = 0, len = arguments.length; i < len; i++) {
                formattedString = replaceAll(formattedString, '{' + i + '}', arguments[i]);
              }
              return formattedString;
            } :
            s[k];
        }();
      }
    }
  }
}(window));
