// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var AppMainCtrl, BaseCtrl, appControllers,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseCtrl = require('scripts/BaseClasses/BaseController.coffee');

  appControllers = angular.module('app_controllers');

  module.exports = AppMainCtrl = (function(superClass) {
    extend(AppMainCtrl, superClass);

    function AppMainCtrl() {
      return AppMainCtrl.__super__.constructor.apply(this, arguments);
    }

    AppMainCtrl.register(appControllers);

    AppMainCtrl.inject('$scope', 'appSidebarState');

    AppMainCtrl.prototype.initialize = function() {
      this.width = 'col-md-9';
      return this.$scope.$on('update view', (function(_this) {
        return function() {
          if (_this.appSidebarState.sidebar === 'visible' && _this.appSidebarState.history === 'hidden') {
            return _this.width = 'col-md-9';
          } else {
            return _this.width = 'col-md-11';
          }
        };
      })(this));
    };

    return AppMainCtrl;

  })(BaseCtrl);

}).call(this);

//# sourceMappingURL=AppMainCtrl.js.map
