// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var AppMenubarDirective, BaseDirective, dirsMod,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseDirective = require('scripts/BaseClasses/BaseDirective');

  module.extend = AppMenubarDirective = (function(superClass) {
    extend(AppMenubarDirective, superClass);

    function AppMenubarDirective() {
      return AppMenubarDirective.__super__.constructor.apply(this, arguments);
    }

    AppMenubarDirective.prototype.initialize = function() {
      this.restrict = 'E';
      return this.template = require('partials/analysis-nav.jade')();
    };

    return AppMenubarDirective;

  })(BaseDirective);

  dirsMod = angular.module('app_directives');

  AppMenubarDirective.register(dirsMod, 'menubar');

}).call(this);

//# sourceMappingURL=AppMenubarDirective.js.map
