// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var AppMessageMap;

  module.exports = AppMessageMap = (function() {
    function AppMessageMap() {
      this._msgMap = [
        {
          msgFrom: 'saveData',
          scopeFrom: ['app_analysis_getData', 'app_analysis_dataWrangler'],
          msgTo: 'save table',
          scopeTo: ['app_analysis_database']
        }, {
          msgFrom: 'infer data types',
          scopeFrom: ['app_analysis_getData', 'app_analysis_dataWrangler', 'app_analysis_cluster', 'app_analysis_charts', 'app_analysis_reliability'],
          msgTo: 'infer all types',
          scopeTo: ['app_analysis_datalib']
        }, {
          msgFrom: 'all types inferred',
          scopeFrom: ['app_analysis_datalib'],
          msgTo: 'data types inferred',
          scopeTo: ['app_analysis_getData', 'app_analysis_dataWrangler', 'app_analysis_cluster', 'app_analysis_charts', 'app_analysis_reliability']
        }, {
          msgFrom: 'getData',
          scopeFrom: ['app_analysis_cluster', 'app_analysis_getData', 'app_analysis_dataWrangler', 'app_analysis_charts', 'app_analysis_reliability'],
          msgTo: 'get table',
          scopeTo: ['app_analysis_database']
        }, {
          msgFrom: 'take table',
          scopeFrom: ['app_analysis_database'],
          msgTo: 'takeTable',
          scopeTo: ['app_analysis_cluster', 'app_analysis_getData', 'app_analysis_dataWrangler', 'app_analysis_charts', 'app_analysis_reliability']
        }
      ];
    }

    AppMessageMap.prototype.getMap = function() {
      return this._msgMap;
    };

    return AppMessageMap;

  })();

}).call(this);

//# sourceMappingURL=AppMessageMap.js.map
