// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';
  var AppSidebarCtrl, BaseCtrl, appControllers,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseCtrl = require('scripts/BaseClasses/BaseController.coffee');

  appControllers = angular.module('app_controllers');

  appControllers.value('appSidebarState', {
    sidebar: 'visible',
    history: 'hidden'
  });

  module.exports = AppSidebarCtrl = (function(superClass) {
    extend(AppSidebarCtrl, superClass);

    function AppSidebarCtrl() {
      return AppSidebarCtrl.__super__.constructor.apply(this, arguments);
    }

    AppSidebarCtrl.register(appControllers);

    AppSidebarCtrl.inject('$scope', 'appSidebarState');

    AppSidebarCtrl.prototype.initialize = function() {
      console.log('controller block for sidebarCtrl');
      this.state = 'show';
      this.arrowDirection = 'glyphicon glyphicon-chevron-left';
      this.activeProjectName = 'default';
      return this.$scope.$on('toggle sidebar', (function(_this) {
        return function(event, results) {
          return _this.toggle();
        };
      })(this));
    };

    AppSidebarCtrl.prototype.view = function() {
      if (this.state === 'show') {
        return true;
      } else {
        return false;
      }
    };

    AppSidebarCtrl.prototype.toggle = function() {
      if (this.state === 'hidden') {
        this.state = 'show';
        this.appSidebarState.sidebar = 'visible';
        this.arrowDirection = 'glyphicon glyphicon-chevron-left';
      } else {
        this.state = 'hidden';
        this.appSidebarState.sidebar = 'hidden';
        this.arrowDirection = 'glyphicon glyphicon-chevron-right';
      }
      return this.$scope.$emit('change in view');
    };

    AppSidebarCtrl.prototype.getClass = function() {
      if (this.state === 'hidden') {
        return 'col-md-1';
      } else {
        return 'col-md-3';
      }
    };

    return AppSidebarCtrl;

  })(BaseCtrl);

}).call(this);

//# sourceMappingURL=AppSidebarCtrl.js.map
