// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';

  /* Filters */
  angular.module('app_filters', []).filter('interpolate', [
    'version', function(version) {
      return function(text) {
        return String(text).replace(/\%VERSION\%/mg, version);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=filters.js.map
