// Generated by CoffeeScript 1.12.2
(function() {
  'use strict';

  /* Sevices */
  var services;

  services = angular.module('app_services', []);

  services.factory('version', function() {
    return "v0.1.5-alpha.2";
  });

}).call(this);

//# sourceMappingURL=services.js.map
